import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import pg from 'pg';
import { buildApp } from '../src/app.js';

const enabled = Boolean(process.env.DATABASE_URL && process.env.AUTH_SECRET);
const suite = enabled ? describe : describe.skip;
const pool = enabled ? new pg.Pool({ connectionString: process.env.DATABASE_URL }) : null;
const app = enabled ? buildApp() : null;

async function login(username: string, password: string) {
  const response = await app!.inject({ method: 'POST', url: '/api/v1/auth/login', payload: { username, password } });
  expect(response.statusCode).toBe(200);
  return { authorization: `Bearer ${response.json().token}` };
}

suite('centralized authorization scope', () => {
  let organizationA = ''; let organizationB = ''; let institutionA = ''; let institutionB = '';
  beforeAll(async () => {
    await app!.ready();
    const organizations = await pool!.query("SELECT id FROM organizations WHERE code IN ('WILAYA-01','WILAYA-02') ORDER BY code");
    const institutions = await pool!.query("SELECT id,organization_id FROM educational_institutions WHERE organization_id = ANY($1::uuid[]) ORDER BY organization_id,id", [organizations.rows.map((row) => row.id)]);
    organizationA = organizations.rows[0]?.id ?? ''; organizationB = organizations.rows[1]?.id ?? '';
    institutionA = institutions.rows.find((row) => row.organization_id === organizationA)?.id ?? '';
    institutionB = institutions.rows.find((row) => row.organization_id === organizationB)?.id ?? '';
  });
  afterAll(async () => { await app?.close(); await pool?.end(); });

  it('allows national access and filters association collections by organization', async () => {
    expect(organizationA).toBeTruthy(); expect(organizationB).toBeTruthy(); expect(institutionA).toBeTruthy(); expect(institutionB).toBeTruthy();
    const national = await login('demo.admin', 'NssmsDemoAdmin-2026!');
    const all = await app!.inject({ method: 'GET', url: '/api/v1/admin/institutions', headers: national });
    expect(all.statusCode).toBe(200); expect(all.json().data.some((row: any) => row.id === institutionB)).toBe(true);
    const association = await login('assoc.w01.admin', 'NssmsAssoc-W01-2026!');
    const scoped = await app!.inject({ method: 'GET', url: '/api/v1/admin/institutions', headers: association });
    expect(scoped.statusCode).toBe(200); expect(scoped.json().data.every((row: any) => row.organization_id === organizationA)).toBe(true);
    const idor = await app!.inject({ method: 'PATCH', url: `/api/v1/admin/institutions/${institutionB}`, headers: association, payload: { name: 'IDOR attempt' } });
    expect(idor.statusCode).toBe(403);
  });

  it('keeps daira and institution users inside their assigned hierarchy', async () => {
    const daira = await login('daira.001.admin', 'NssmsDaira-001-2026!');
    const dairaInstitutions = await app!.inject({ method: 'GET', url: '/api/v1/admin/institutions', headers: daira });
    expect(dairaInstitutions.statusCode).toBe(200); expect(dairaInstitutions.json().data.every((row: any) => row.daira_id === 1)).toBe(true);
    const institution = await login('institution.001.demo', 'NssmsInst-001-2026!');
    const me = await app!.inject({ method: 'GET', url: '/api/v1/auth/me', headers: institution });
    const own = await app!.inject({ method: 'GET', url: '/api/v1/admin/institutions', headers: institution });
    expect(own.statusCode).toBe(200); expect(own.json().data.every((row: any) => row.id === me.json().user.institutionId)).toBe(true);
    const denied = await app!.inject({ method: 'PATCH', url: `/api/v1/admin/institutions/${institutionB}`, headers: institution, payload: { name: 'IDOR attempt' } });
    expect(denied.statusCode).toBe(403);
  });

  it('prevents cross-organization participant reads and direct writes', async () => {
    const national = await login('demo.admin', 'NssmsDemoAdmin-2026!');
    const created = await app!.inject({ method: 'POST', url: '/api/v1/admin/participants', headers: national, payload: { institutionId: institutionB, givenName: 'Scope', familyName: `Isolation-${Date.now()}` } });
    expect(created.statusCode).toBe(201); const participantId = created.json().data.id;
    const associationA = await login('assoc.w01.admin', 'NssmsAssoc-W01-2026!');
    const associationB = await login('assoc.w02.admin', 'NssmsAssoc-W02-2026!');
    const foreignRead = await app!.inject({ method: 'GET', url: '/api/v1/admin/participants', headers: associationA });
    expect(foreignRead.statusCode).toBe(200); expect(foreignRead.json().data.some((row: any) => row.id === participantId)).toBe(false);
    const ownRead = await app!.inject({ method: 'GET', url: '/api/v1/admin/participants', headers: associationB });
    expect(ownRead.statusCode).toBe(200); expect(ownRead.json().data.some((row: any) => row.id === participantId)).toBe(true);
    const foreignWrite = await app!.inject({ method: 'PATCH', url: `/api/v1/admin/participants/${participantId}`, headers: associationA, payload: { givenName: 'Blocked' } });
    expect(foreignWrite.statusCode).toBe(403);
  });
  it('enforces institution scope and participant context when creating individual entries', async () => {
    const institution = await login('institution.001.demo', 'NssmsInst-001-2026!'); const me = await app!.inject({ method:'GET',url:'/api/v1/auth/me',headers:institution }); const ownInstitution=me.json().user.institutionId as string;
    await pool!.query("insert into role_permissions(role_id,permission_id) select ur.role_id,p.id from user_roles ur join permissions p on p.key='result.manage' where ur.user_id=$1 on conflict do nothing",[me.json().user.id]);
    const foreign=(await pool!.query('select id from educational_institutions where id<>$1 limit 1',[ownInstitution])).rows[0].id,tag=`A1-${Date.now()}`,season=(await pool!.query("insert into seasons(name,start_date,end_date) values($1,'2070-01-01','2070-12-31') returning id",[tag])).rows[0].id,programme=(await pool!.query("insert into competition_programmes(season_id,code,title,effective_from) values($1,$2,$2,'2070-01-01') returning id",[season,tag])).rows[0].id,version=(await pool!.query("insert into regulation_versions(version_no,programme_id,effective_period) values('1',$1,'[2070-01-01,2071-01-01)') returning id",[programme])).rows[0].id,competition=(await pool!.query('insert into competitions(season_id,name) values($1,$2) returning id',[season,tag])).rows[0].id,stage=(await pool!.query("insert into competition_stages(competition_id,programme_id,regulation_version_id,stage_level_code) values($1,$2,$3,'W') returning id",[competition,programme,version])).rows[0].id,category=(await pool!.query("insert into categories(programme_id,code,name,gender_code,regulation_version_id) values($1,$2,$2,'OPEN',$3) returning id",[programme,tag,version])).rows[0].id,ownParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Own') returning id",[ownInstitution])).rows[0].id,foreignParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Foreign') returning id",[foreign])).rows[0].id;
    const body=(institutionId:string,participantId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,participantId}); const own=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:institution,payload:body(ownInstitution,ownParticipant)});expect(own.statusCode).toBe(200); const before=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;
    for(const payload of [body(foreign,foreignParticipant),body(ownInstitution,foreignParticipant)]){const response=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:institution,payload});expect([403,422]).toContain(response.statusCode);expect(response.json().error).toMatch(/forbidden|invalid_context/)} const after=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;expect(after).toBe(before);expect((await pool!.query('select count(*)::int as count from individual_entries i join competition_entries e on e.id=i.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(1);
  });
  it('enforces institution scope and team context when creating team entries', async () => {
    const institution = await login('institution.001.demo', 'NssmsInst-001-2026!'); const me = await app!.inject({ method:'GET',url:'/api/v1/auth/me',headers:institution }); const ownInstitution=me.json().user.institutionId as string;
    const foreign=(await pool!.query('select id from educational_institutions where id<>$1 limit 1',[ownInstitution])).rows[0].id,tag=`A1T-${Date.now()}`,season=(await pool!.query("insert into seasons(name,start_date,end_date) values($1,'2069-01-01','2069-12-31') returning id",[tag])).rows[0].id,programme=(await pool!.query("insert into competition_programmes(season_id,code,title,effective_from) values($1,$2,$2,'2069-01-01') returning id",[season,tag])).rows[0].id,version=(await pool!.query("insert into regulation_versions(version_no,programme_id,effective_period) values('1',$1,'[2069-01-01,2070-01-01)') returning id",[programme])).rows[0].id,competition=(await pool!.query('insert into competitions(season_id,name) values($1,$2) returning id',[season,tag])).rows[0].id,stage=(await pool!.query("insert into competition_stages(competition_id,programme_id,regulation_version_id,stage_level_code) values($1,$2,$3,'W') returning id",[competition,programme,version])).rows[0].id,category=(await pool!.query("insert into categories(programme_id,code,name,gender_code,regulation_version_id) values($1,$2,$2,'OPEN',$3) returning id",[programme,tag,version])).rows[0].id,ownTeam=(await pool!.query("insert into teams(institution_id,category_id,stage_id,name) values($1,$2,$3,'Own Team') returning id",[ownInstitution,category,stage])).rows[0].id,foreignTeam=(await pool!.query("insert into teams(institution_id,category_id,stage_id,name) values($1,$2,$3,'Foreign Team') returning id",[foreign,category,stage])).rows[0].id;
    const body=(institutionId:string,teamId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,teamId}); const own=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:institution,payload:body(ownInstitution,ownTeam)});expect(own.statusCode).toBe(200); const before=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;
    for(const payload of [body(foreign,foreignTeam),body(ownInstitution,foreignTeam)]){const response=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:institution,payload});expect([403,422]).toContain(response.statusCode);expect(response.json().error).toMatch(/forbidden|invalid_context/)} const after=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;expect(after).toBe(before);expect((await pool!.query('select count(*)::int as count from team_entries t join competition_entries e on e.id=t.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(1);
  });
  it('allows association entry creation only for resources inside its organization scope', async () => {
    const association=await login('assoc.w01.admin','NssmsAssoc-W01-2026!'),tag=`A1A-${Date.now()}`,ownInstitution=institutionA,foreignInstitution=institutionB,season=(await pool!.query("insert into seasons(name,start_date,end_date) values($1,'2068-01-01','2068-12-31') returning id",[tag])).rows[0].id,programme=(await pool!.query("insert into competition_programmes(season_id,code,title,effective_from) values($1,$2,$2,'2068-01-01') returning id",[season,tag])).rows[0].id,version=(await pool!.query("insert into regulation_versions(version_no,programme_id,effective_period) values('1',$1,'[2068-01-01,2069-01-01)') returning id",[programme])).rows[0].id,competition=(await pool!.query('insert into competitions(season_id,name) values($1,$2) returning id',[season,tag])).rows[0].id,stage=(await pool!.query("insert into competition_stages(competition_id,programme_id,regulation_version_id,stage_level_code) values($1,$2,$3,'W') returning id",[competition,programme,version])).rows[0].id,category=(await pool!.query("insert into categories(programme_id,code,name,gender_code,regulation_version_id) values($1,$2,$2,'OPEN',$3) returning id",[programme,tag,version])).rows[0].id,ownParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Association Own') returning id",[ownInstitution])).rows[0].id,foreignParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Association Foreign') returning id",[foreignInstitution])).rows[0].id,foreignTeam=(await pool!.query("insert into teams(institution_id,category_id,stage_id,name) values($1,$2,$3,'Association Foreign Team') returning id",[foreignInstitution,category,stage])).rows[0].id;
    const individual=(institutionId:string,participantId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,participantId}),team=(institutionId:string,teamId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,teamId}); const own=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:association,payload:individual(ownInstitution,ownParticipant)});expect(own.statusCode).toBe(200); const before=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;
    for(const payload of [individual(foreignInstitution,foreignParticipant),individual(ownInstitution,foreignParticipant),team(ownInstitution,foreignTeam)]){const response=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:association,payload});expect([403,422]).toContain(response.statusCode);expect(response.json().error).toMatch(/forbidden|invalid_context/)} expect((await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count).toBe(before);expect((await pool!.query('select count(*)::int as count from individual_entries i join competition_entries e on e.id=i.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(1);expect((await pool!.query('select count(*)::int as count from team_entries t join competition_entries e on e.id=t.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(0);
  });
  it('allows daira entry creation only for resources inside its daira scope', async () => {
    const daira=await login('daira.001.admin','NssmsDaira-001-2026!'),me=await app!.inject({method:'GET',url:'/api/v1/auth/me',headers:daira}),ownDaira=me.json().user.dairaId as string,ownInstitution=(await pool!.query('select id from educational_institutions where daira_id=$1 limit 1',[ownDaira])).rows[0].id,foreignInstitution=(await pool!.query('select id from educational_institutions where daira_id<>$1 limit 1',[ownDaira])).rows[0].id,tag=`A1D-${Date.now()}`,season=(await pool!.query("insert into seasons(name,start_date,end_date) values($1,'2067-01-01','2067-12-31') returning id",[tag])).rows[0].id,programme=(await pool!.query("insert into competition_programmes(season_id,code,title,effective_from) values($1,$2,$2,'2067-01-01') returning id",[season,tag])).rows[0].id,version=(await pool!.query("insert into regulation_versions(version_no,programme_id,effective_period) values('1',$1,'[2067-01-01,2068-01-01)') returning id",[programme])).rows[0].id,competition=(await pool!.query('insert into competitions(season_id,name) values($1,$2) returning id',[season,tag])).rows[0].id,stage=(await pool!.query("insert into competition_stages(competition_id,programme_id,regulation_version_id,stage_level_code) values($1,$2,$3,'W') returning id",[competition,programme,version])).rows[0].id,category=(await pool!.query("insert into categories(programme_id,code,name,gender_code,regulation_version_id) values($1,$2,$2,'OPEN',$3) returning id",[programme,tag,version])).rows[0].id,ownParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Daira Own') returning id",[ownInstitution])).rows[0].id,foreignParticipant=(await pool!.query("insert into participants(institution_id,given_name) values($1,'Daira Foreign') returning id",[foreignInstitution])).rows[0].id,foreignTeam=(await pool!.query("insert into teams(institution_id,category_id,stage_id,name) values($1,$2,$3,'Daira Foreign Team') returning id",[foreignInstitution,category,stage])).rows[0].id;
    const individual=(institutionId:string,participantId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,participantId}),team=(institutionId:string,teamId:string)=>({stageId:stage,categoryId:category,institutionId,regulationVersionId:version,teamId}); const own=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:daira,payload:individual(ownInstitution,ownParticipant)});expect(own.statusCode).toBe(200); const before=(await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count;
    for(const payload of [individual(foreignInstitution,foreignParticipant),individual(ownInstitution,foreignParticipant),team(ownInstitution,foreignTeam)]){const response=await app!.inject({method:'POST',url:'/api/v1/admin/competition-entries',headers:daira,payload});expect([403,422]).toContain(response.statusCode);expect(response.json().error).toMatch(/forbidden|invalid_context/)} expect((await pool!.query('select count(*)::int as count from competition_entries where stage_id=$1',[stage])).rows[0].count).toBe(before);expect((await pool!.query('select count(*)::int as count from individual_entries i join competition_entries e on e.id=i.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(1);expect((await pool!.query('select count(*)::int as count from team_entries t join competition_entries e on e.id=t.competition_entry_id where e.stage_id=$1',[stage])).rows[0].count).toBe(0);
  });
});
