import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import pg from 'pg';
import { buildApp } from '../src/app.js';

const enabled = Boolean(process.env.DATABASE_URL && process.env.AUTH_SECRET);
const suite = enabled ? describe : describe.skip;
const pool = enabled ? new pg.Pool({ connectionString: process.env.DATABASE_URL }) : null;
const app = enabled ? buildApp() : null;
async function login(username: string, password: string) { const response = await app!.inject({ method: 'POST', url: '/api/v1/auth/login', payload: { username, password } }); expect(response.statusCode).toBe(200); return { authorization: `Bearer ${response.json().token}` }; }
async function roleId(name: string) { return (await pool!.query('SELECT id FROM roles WHERE name=$1', [name])).rows[0].id as string; }
async function target(role: string, fields: { organizationId?: string; dairaId?: number; institutionId?: string } = {}) { const row = (await pool!.query('INSERT INTO users(username,display_name,password_hash,organization_id,daira_id,institution_id) VALUES($1,$2,NULL,$3,$4,$5) RETURNING id', [`scope-target-${Date.now()}-${Math.random().toString(16).slice(2)}`, 'Scope target', fields.organizationId ?? null, fields.dairaId ?? null, fields.institutionId ?? null])).rows[0]; await pool!.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2)', [row.id, await roleId(role)]); return row.id as string; }

suite('admin user scope assignment', () => {
  let system: { authorization: string }; let association = ''; let otherAssociation = ''; let institution = ''; let institutionOther = '';
  beforeAll(async () => { await app!.ready(); system = await login('demo.admin', 'NssmsDemoAdmin-2026!'); const orgs = (await pool!.query("SELECT id FROM organizations WHERE code IN ('WILAYA-01','WILAYA-02') ORDER BY code")).rows; const insts = (await pool!.query('SELECT id,organization_id FROM educational_institutions WHERE organization_id=ANY($1::uuid[]) ORDER BY organization_id,id', [orgs.map(row => row.id)])).rows; association = await target('ASSOCIATION_ADMINISTRATOR', { organizationId: orgs[0].id }); otherAssociation = await target('ASSOCIATION_ADMINISTRATOR', { organizationId: orgs[1].id }); institution = insts.find(row => row.organization_id === orgs[0].id).id; institutionOther = insts.find(row => row.organization_id === orgs[1].id).id; });
  afterAll(async () => { await app?.close(); await pool?.end(); });
  it('reads and assigns national, association, daira, and institution scopes', async () => {
    const nationalTarget = await target('SYSTEM_ADMINISTRATOR'); const national = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${nationalTarget}/scope`, headers: system, payload: { scopeType: 'NATIONAL', scopeId: null } }); expect(national.statusCode).toBe(200); expect(national.json().data.scopeType).toBe('NATIONAL');
    const association = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${otherAssociation}/scope`, headers: system, payload: { scopeType: 'ASSOCIATION', scopeId: (await pool!.query("SELECT id FROM organizations WHERE code='WILAYA-02'")).rows[0].id } }); expect(association.statusCode).toBe(200); expect(association.json().data.scopeType).toBe('ASSOCIATION');
    const dairaTarget = await target('DAIRA_OFFICER'); const daira = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${dairaTarget}/scope`, headers: system, payload: { scopeType: 'DAIRA', scopeId: '1' } }); expect(daira.statusCode).toBe(200);
    const institutionTarget = await target('MEMBER_INSTITUTION_USER'); const inst = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${institutionTarget}/scope`, headers: system, payload: { scopeType: 'INSTITUTION', scopeId: institution } }); expect(inst.statusCode).toBe(200);
  });
  it('rejects incompatible, nonexistent, and inaccessible scope mutations', async () => {
    const incompatible = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${association}/scope`, headers: system, payload: { scopeType: 'DAIRA', scopeId: '1' } }); expect(incompatible.statusCode).toBe(409); expect(incompatible.json().error).toBe('incompatible_role_scope');
    const missing = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${association}/scope`, headers: system, payload: { scopeType: 'ASSOCIATION', scopeId: '00000000-0000-0000-0000-000000000000' } }); expect(missing.statusCode).toBe(404); expect(missing.json().error).toBe('scope_not_found');
    const scopedAdmin = await login('assoc.w01.admin', 'NssmsAssoc-W01-2026!'); const denied = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${otherAssociation}/scope`, headers: scopedAdmin, payload: { scopeType: 'ASSOCIATION', scopeId: (await pool!.query("SELECT id FROM organizations WHERE code='WILAYA-02'")).rows[0].id } }); expect(denied.statusCode).toBe(403);
  });
  it('updates roles and scope atomically and audits the prior/new scope', async () => { const user = await target('ASSOCIATION_ADMINISTRATOR'); const result = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${user}/access`, headers: system, payload: { roleIds: [await roleId('DAIRA_OFFICER')], scopeType: 'DAIRA', scopeId: '1' } }); expect(result.statusCode).toBe(200); const row = (await pool!.query('SELECT organization_id,daira_id,institution_id FROM users WHERE id=$1',[user])).rows[0]; expect(row.organization_id).toBeNull(); expect(row.daira_id).toBe(1); expect(row.institution_id).toBeNull(); expect((await pool!.query("SELECT metadata FROM audit_logs WHERE action='UPDATE_ACCESS' AND entity_id=$1 ORDER BY occurred_at DESC LIMIT 1",[user])).rowCount).toBe(1); });
  it('rejects unauthenticated and scoped callers, and prevents stale role scope', async () => { const unauth = await app!.inject({ method: 'GET', url: `/api/v1/admin/users/${association}/scope` }); expect(unauth.statusCode).toBe(401); const scoped = await login('assoc.w01.admin', 'NssmsAssoc-W01-2026!'); const forbidden = await app!.inject({ method: 'GET', url: `/api/v1/admin/users/${association}/scope`, headers: scoped }); expect(forbidden.statusCode).toBe(403); const stale = await app!.inject({ method: 'PUT', url: `/api/v1/admin/users/${association}/roles`, headers: system, payload: { roleIds: [await roleId('DAIRA_OFFICER')] } }); expect(stale.statusCode).toBe(409); });
  it('returns safe scope DTOs without password hashes or tokens', async () => { const response = await app!.inject({ method: 'GET', url: '/api/v1/admin/users', headers: system }); expect(response.statusCode).toBe(200); expect(response.json().data.length).toBeGreaterThan(0); for (const row of response.json().data) { expect(row).not.toHaveProperty('password_hash'); expect(row).not.toHaveProperty('token'); expect(row).toHaveProperty('scope_type'); } const scope = await app!.inject({ method: 'GET', url: `/api/v1/admin/users/${association}/scope`, headers: system }); expect(scope.statusCode).toBe(200); expect(scope.json().data).not.toHaveProperty('password_hash'); expect(scope.json().data).not.toHaveProperty('token'); });
  it('protects user endpoints from unauthorized creation and missing targets', async () => { const unauth = await app!.inject({ method: 'POST', url: '/api/v1/admin/users', payload: { username: 'blocked-user', displayName: 'Blocked', password: 'A-long-password-2026!', roleIds: [await roleId('DAIRA_OFFICER')] } }); expect(unauth.statusCode).toBe(401); const missing = await app!.inject({ method: 'GET', url: '/api/v1/admin/users/00000000-0000-0000-0000-000000000000/scope', headers: system }); expect(missing.statusCode).toBe(404); });
  it('maintains profile safely and audits changed fields', async () => { const username = `profile-target-${Date.now()}`; const created = await app!.inject({ method: 'POST', url: '/api/v1/admin/users', headers: system, payload: { username, displayName: 'قبل', password: 'Old-Password-2026!', roleIds: [await roleId('PUBLIC_USER')] } }); expect(created.statusCode).toBe(201); const id=created.json().data.id; const updated=await app!.inject({ method:'PATCH', url:`/api/v1/admin/users/${id}/profile`, headers:system, payload:{displayName:'بعد'}}); expect(updated.statusCode).toBe(200); expect(updated.json().data.display_name).toBe('بعد'); expect(updated.json().data).not.toHaveProperty('password_hash'); expect((await pool!.query("SELECT metadata FROM audit_logs WHERE action='PROFILE_UPDATE' AND entity_id=$1 ORDER BY occurred_at DESC LIMIT 1",[id])).rowCount).toBe(1); });
  it('resets passwords without exposing secrets and gates authentication', async () => { const username = `password-target-${Date.now()}`; const created = await app!.inject({ method: 'POST', url: '/api/v1/admin/users', headers: system, payload: { username, displayName: 'Password Target', password: 'Old-Password-2026!', roleIds: [await roleId('PUBLIC_USER')] } }); const id=created.json().data.id; const reset=await app!.inject({ method:'POST', url:`/api/v1/admin/users/${id}/password-reset`, headers:system, payload:{password:'New-Password-2026!'}}); expect(reset.statusCode).toBe(200); expect(reset.json().data).not.toHaveProperty('password_hash'); expect((await app!.inject({method:'POST',url:'/api/v1/auth/login',payload:{username,password:'Old-Password-2026!'}})).statusCode).toBe(401); expect((await app!.inject({method:'POST',url:'/api/v1/auth/login',payload:{username,password:'New-Password-2026!'}})).statusCode).toBe(200); const audit=(await pool!.query("SELECT metadata::text FROM audit_logs WHERE action='PASSWORD_RESET' AND entity_id=$1 ORDER BY occurred_at DESC LIMIT 1",[id])).rows[0].metadata; expect(audit).not.toMatch(/Old-Password|New-Password|scrypt|password_hash/i); });
  it('disables and re-enables authentication and rejects weak resets', async () => { const username = `status-target-${Date.now()}`; const created = await app!.inject({ method: 'POST', url: '/api/v1/admin/users', headers: system, payload: { username, displayName: 'Status Target', password: 'Status-Password-2026!', roleIds: [await roleId('PUBLIC_USER')] } }); const id=created.json().data.id; expect((await app!.inject({method:'POST',url:`/api/v1/admin/users/${id}/password-reset`,headers:system,payload:{password:'short'}})).statusCode).toBe(400); expect((await app!.inject({method:'POST',url:`/api/v1/admin/users/${id}/status`,headers:system,payload:{status:'DISABLED'}})).statusCode).toBe(200); expect((await app!.inject({method:'POST',url:'/api/v1/auth/login',payload:{username,password:'Status-Password-2026!'}})).statusCode).toBe(401); expect((await app!.inject({method:'POST',url:`/api/v1/admin/users/${id}/status`,headers:system,payload:{status:'ACTIVE'}})).statusCode).toBe(200); expect((await app!.inject({method:'POST',url:'/api/v1/auth/login',payload:{username,password:'Status-Password-2026!'}})).statusCode).toBe(200); const audits=(await pool!.query("SELECT action FROM audit_logs WHERE entity_id=$1 AND action IN ('ENABLE','DISABLE')",[id])).rows.map(row=>row.action); expect(audits).toEqual(expect.arrayContaining(['ENABLE','DISABLE'])); });
});
