-- NSSMS-ARCH-013 corrective lifecycle and evidence enforcement.
CREATE OR REPLACE FUNCTION nssms_rank_draft_only() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE bad boolean; BEGIN
 IF TG_OP='INSERT' THEN IF NEW.status<>'DRAFT' OR NEW.archived_at IS NOT NULL THEN RAISE EXCEPTION 'new ranking snapshots must begin in DRAFT'; END IF; RETURN NEW; END IF;
 IF TG_OP='DELETE' THEN IF OLD.status<>'DRAFT' THEN RAISE EXCEPTION 'official rankings cannot be deleted'; END IF; RETURN OLD; END IF;
 IF NOT ((OLD.status='DRAFT' AND NEW.status IN ('DRAFT','VALIDATED')) OR (OLD.status='VALIDATED' AND NEW.status IN ('VALIDATED','PUBLISHED','ARCHIVED')) OR (OLD.status='PUBLISHED' AND NEW.status IN ('PUBLISHED','ARCHIVED')) OR (OLD.status='ARCHIVED' AND NEW.status='ARCHIVED')) THEN RAISE EXCEPTION 'ranking lifecycle transitions must be forward-only'; END IF;
 IF OLD.status IN ('VALIDATED','PUBLISHED','ARCHIVED') AND (NEW.stage_id IS DISTINCT FROM OLD.stage_id OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id OR NEW.event_id IS DISTINCT FROM OLD.event_id OR NEW.category_id IS DISTINCT FROM OLD.category_id OR NEW.regulation_version_id IS DISTINCT FROM OLD.regulation_version_id OR NEW.ranking_type IS DISTINCT FROM OLD.ranking_type OR NEW.calculation_version IS DISTINCT FROM OLD.calculation_version OR NEW.calculation_metadata IS DISTINCT FROM OLD.calculation_metadata OR NEW.supersedes_ranking_id IS DISTINCT FROM OLD.supersedes_ranking_id) THEN RAISE EXCEPTION 'official ranking snapshots are immutable'; END IF;
 IF OLD.status='DRAFT' AND NEW.status='VALIDATED' THEN
  IF NOT EXISTS(SELECT 1 FROM ranking_inputs WHERE ranking_id=NEW.id) OR NOT EXISTS(SELECT 1 FROM ranking_rows WHERE ranking_id=NEW.id) THEN RAISE EXCEPTION 'validated rankings require inputs and rows'; END IF;
  SELECT EXISTS(SELECT 1 FROM ranking_inputs i JOIN results x ON x.id=i.result_id JOIN result_validations v ON v.id=i.result_validation_id WHERE i.ranking_id=NEW.id AND (v.result_id IS DISTINCT FROM x.id OR v.decision<>'VALIDATED' OR x.governed_status<>'VALIDATED' OR x.stage_id IS DISTINCT FROM NEW.stage_id OR x.event_id IS DISTINCT FROM NEW.event_id OR x.category_id IS DISTINCT FROM NEW.category_id OR x.regulation_version_id IS DISTINCT FROM NEW.regulation_version_id OR EXISTS(SELECT 1 FROM result_validations s WHERE s.supersedes_validation_id=v.id) OR v.revision_no<>(SELECT COALESCE(MAX(revision_no),0) FROM result_revisions WHERE result_id=x.id))) INTO bad; IF bad THEN RAISE EXCEPTION 'ranking validation input is stale or invalid'; END IF;
  IF EXISTS(SELECT 1 FROM ranking_rows row WHERE row.ranking_id=NEW.id AND NOT EXISTS(SELECT 1 FROM ranking_inputs i JOIN results x ON x.id=i.result_id WHERE i.ranking_id=NEW.id AND x.competition_entry_id=row.competition_entry_id)) THEN RAISE EXCEPTION 'ranking rows require supporting inputs'; END IF;
 END IF;
 IF NEW.status='ARCHIVED' AND OLD.status<>'ARCHIVED' THEN IF NEW.archived_at IS NOT NULL OR OLD.archived_at IS NOT NULL THEN RAISE EXCEPTION 'ranking archive timestamp is database-controlled'; END IF; NEW.archived_at:=now(); ELSIF NEW.archived_at IS DISTINCT FROM OLD.archived_at THEN RAISE EXCEPTION 'ranking archive timestamp is database-controlled'; END IF; RETURN NEW; END; $$;
CREATE OR REPLACE FUNCTION nssms_award_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='INSERT' THEN IF NEW.status<>'DRAFT' OR NEW.issued_at IS NOT NULL OR NEW.revoked_at IS NOT NULL OR NEW.archived_at IS NOT NULL THEN RAISE EXCEPTION 'new awards must begin in DRAFT'; END IF; RETURN NEW; END IF;
 IF TG_OP='DELETE' THEN IF OLD.status<>'DRAFT' THEN RAISE EXCEPTION 'governed awards cannot be deleted'; END IF; RETURN OLD; END IF;
 IF NOT ((OLD.status='DRAFT' AND NEW.status IN ('DRAFT','ISSUED','ARCHIVED')) OR (OLD.status='ISSUED' AND NEW.status IN ('ISSUED','REVOKED','ARCHIVED')) OR (OLD.status='REVOKED' AND NEW.status IN ('REVOKED','ARCHIVED')) OR (OLD.status='ARCHIVED' AND NEW.status='ARCHIVED')) THEN RAISE EXCEPTION 'award lifecycle transitions must be forward-only'; END IF;
 IF OLD.status IN ('ISSUED','REVOKED','ARCHIVED') AND (NEW.ranking_id IS DISTINCT FROM OLD.ranking_id OR NEW.competition_entry_id IS DISTINCT FROM OLD.competition_entry_id OR NEW.regulation_version_id IS DISTINCT FROM OLD.regulation_version_id OR NEW.award_type IS DISTINCT FROM OLD.award_type OR NEW.label IS DISTINCT FROM OLD.label OR NEW.issued_by_user_id IS DISTINCT FROM OLD.issued_by_user_id OR NEW.issued_at IS DISTINCT FROM OLD.issued_at OR (OLD.status='REVOKED' AND (NEW.revoked_by_user_id IS DISTINCT FROM OLD.revoked_by_user_id OR NEW.revoked_at IS DISTINCT FROM OLD.revoked_at))) THEN RAISE EXCEPTION 'governed awards are immutable'; END IF;
 IF NEW.status='ISSUED' AND OLD.status='DRAFT' THEN IF NEW.ranking_id IS NULL OR NEW.issued_by_user_id IS NULL OR NEW.issued_at IS NOT NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.issued_by_user_id AND status='ACTIVE') OR NOT EXISTS(SELECT 1 FROM rankings r JOIN ranking_rows row ON row.ranking_id=r.id WHERE r.id=NEW.ranking_id AND r.status IN ('VALIDATED','PUBLISHED') AND r.regulation_version_id=NEW.regulation_version_id AND row.competition_entry_id=NEW.competition_entry_id) THEN RAISE EXCEPTION 'award issuance requires active authority and matching official ranking evidence'; END IF; NEW.issued_at:=now(); END IF;
 IF NEW.status='REVOKED' AND OLD.status='ISSUED' THEN IF NEW.revoked_by_user_id IS NULL OR NEW.revoked_at IS NOT NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.revoked_by_user_id AND status='ACTIVE') THEN RAISE EXCEPTION 'award revocation requires active authority'; END IF; NEW.revoked_at:=now(); END IF;
 IF NEW.status='ARCHIVED' AND OLD.status<>'ARCHIVED' THEN IF NEW.archived_at IS NOT NULL THEN RAISE EXCEPTION 'award archive timestamp is database-controlled'; END IF; NEW.archived_at:=now(); ELSIF NEW.archived_at IS DISTINCT FROM OLD.archived_at THEN RAISE EXCEPTION 'award archive timestamp is database-controlled'; END IF; RETURN NEW; END; $$;
