-- NSSMS-ARCH-013: terminal-current ranking chains and award revocation provenance guards.
CREATE OR REPLACE FUNCTION nssms_validate_ranking_supersession() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE parent rankings%ROWTYPE; BEGIN
 IF NEW.supersedes_ranking_id IS NULL THEN RETURN NEW; END IF; IF NEW.supersedes_ranking_id=NEW.id THEN RAISE EXCEPTION 'ranking cannot supersede itself'; END IF;
 SELECT * INTO parent FROM rankings WHERE id=NEW.supersedes_ranking_id FOR UPDATE; IF NOT FOUND OR parent.status NOT IN ('VALIDATED','PUBLISHED') THEN RAISE EXCEPTION 'ranking supersession requires an official parent'; END IF;
 IF parent.stage_id IS DISTINCT FROM NEW.stage_id OR parent.occurrence_id IS DISTINCT FROM NEW.occurrence_id OR parent.event_id IS DISTINCT FROM NEW.event_id OR parent.category_id IS DISTINCT FROM NEW.category_id OR parent.ranking_type IS DISTINCT FROM NEW.ranking_type OR parent.regulation_version_id IS DISTINCT FROM NEW.regulation_version_id THEN RAISE EXCEPTION 'ranking supersession parent must share governed context'; END IF;
 IF EXISTS(SELECT 1 FROM rankings successor WHERE successor.supersedes_ranking_id=parent.id) THEN RAISE EXCEPTION 'ranking supersession parent is no longer current'; END IF; RETURN NEW; END; $$;
CREATE OR REPLACE FUNCTION nssms_award_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='INSERT' THEN IF NEW.status<>'DRAFT' OR NEW.issued_at IS NOT NULL OR NEW.revoked_by_user_id IS NOT NULL OR NEW.revoked_at IS NOT NULL OR NEW.archived_at IS NOT NULL THEN RAISE EXCEPTION 'new awards must begin in DRAFT without governed provenance'; END IF; RETURN NEW; END IF;
 IF TG_OP='DELETE' THEN IF OLD.status<>'DRAFT' THEN RAISE EXCEPTION 'governed awards cannot be deleted'; END IF; RETURN OLD; END IF;
 IF OLD.status IN ('DRAFT','ISSUED') AND NOT (OLD.status='ISSUED' AND NEW.status='REVOKED') AND (NEW.revoked_by_user_id IS NOT NULL OR NEW.revoked_at IS NOT NULL) THEN RAISE EXCEPTION 'award revocation provenance may only be set during issuance revocation'; END IF;
 IF NOT ((OLD.status='DRAFT' AND NEW.status IN ('DRAFT','ISSUED','ARCHIVED')) OR (OLD.status='ISSUED' AND NEW.status IN ('ISSUED','REVOKED','ARCHIVED')) OR (OLD.status='REVOKED' AND NEW.status IN ('REVOKED','ARCHIVED')) OR (OLD.status='ARCHIVED' AND NEW.status='ARCHIVED')) THEN RAISE EXCEPTION 'award lifecycle transitions must be forward-only'; END IF;
 IF OLD.status IN ('ISSUED','REVOKED','ARCHIVED') AND (NEW.ranking_id IS DISTINCT FROM OLD.ranking_id OR NEW.competition_entry_id IS DISTINCT FROM OLD.competition_entry_id OR NEW.regulation_version_id IS DISTINCT FROM OLD.regulation_version_id OR NEW.award_type IS DISTINCT FROM OLD.award_type OR NEW.label IS DISTINCT FROM OLD.label OR NEW.issued_by_user_id IS DISTINCT FROM OLD.issued_by_user_id OR NEW.issued_at IS DISTINCT FROM OLD.issued_at OR (OLD.status='REVOKED' AND (NEW.revoked_by_user_id IS DISTINCT FROM OLD.revoked_by_user_id OR NEW.revoked_at IS DISTINCT FROM OLD.revoked_at))) THEN RAISE EXCEPTION 'governed awards are immutable'; END IF;
 IF NEW.status='ISSUED' AND OLD.status='DRAFT' THEN IF NEW.ranking_id IS NULL OR NEW.issued_by_user_id IS NULL OR NEW.issued_at IS NOT NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.issued_by_user_id AND status='ACTIVE') OR NOT EXISTS(SELECT 1 FROM rankings r JOIN ranking_rows row ON row.ranking_id=r.id WHERE r.id=NEW.ranking_id AND r.status IN ('VALIDATED','PUBLISHED') AND r.regulation_version_id=NEW.regulation_version_id AND row.competition_entry_id=NEW.competition_entry_id) THEN RAISE EXCEPTION 'award issuance requires active authority and matching official ranking evidence'; END IF; NEW.issued_at:=now(); END IF;
 IF NEW.status='REVOKED' AND OLD.status='ISSUED' THEN IF NEW.revoked_by_user_id IS NULL OR NEW.revoked_at IS NOT NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.revoked_by_user_id AND status='ACTIVE') THEN RAISE EXCEPTION 'award revocation requires active authority'; END IF; NEW.revoked_at:=now(); END IF;
 IF NEW.status='ARCHIVED' AND OLD.status<>'ARCHIVED' THEN IF NEW.archived_at IS NOT NULL THEN RAISE EXCEPTION 'award archive timestamp is database-controlled'; END IF; NEW.archived_at:=now(); ELSIF NEW.archived_at IS DISTINCT FROM OLD.archived_at THEN RAISE EXCEPTION 'award archive timestamp is database-controlled'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER rankings_supersession_trg BEFORE INSERT OR UPDATE ON rankings FOR EACH ROW EXECUTE FUNCTION nssms_validate_ranking_supersession();
