-- NSSMS-ARCH-013: supersession is permanent; archived terminals never reactivate ancestors.
CREATE OR REPLACE FUNCTION nssms_validate_ranking_supersession() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE parent rankings%ROWTYPE; other_successor boolean; cycle_exists boolean; BEGIN
 IF NEW.supersedes_ranking_id IS NULL THEN RETURN NEW; END IF; IF NEW.supersedes_ranking_id=NEW.id THEN RAISE EXCEPTION 'ranking cannot supersede itself'; END IF;
 SELECT * INTO parent FROM rankings WHERE id=NEW.supersedes_ranking_id FOR UPDATE; IF NOT FOUND OR parent.status NOT IN ('VALIDATED','PUBLISHED') THEN RAISE EXCEPTION 'ranking supersession requires an active official terminal parent'; END IF;
 IF parent.stage_id IS DISTINCT FROM NEW.stage_id OR parent.occurrence_id IS DISTINCT FROM NEW.occurrence_id OR parent.event_id IS DISTINCT FROM NEW.event_id OR parent.category_id IS DISTINCT FROM NEW.category_id OR parent.ranking_type IS DISTINCT FROM NEW.ranking_type OR parent.regulation_version_id IS DISTINCT FROM NEW.regulation_version_id THEN RAISE EXCEPTION 'ranking supersession parent must share governed context'; END IF;
 WITH RECURSIVE ancestors(id) AS (SELECT supersedes_ranking_id FROM rankings WHERE id=parent.id UNION ALL SELECT r.supersedes_ranking_id FROM rankings r JOIN ancestors a ON r.id=a.id WHERE a.id IS NOT NULL) SELECT EXISTS(SELECT 1 FROM ancestors WHERE id=NEW.id) INTO cycle_exists; IF cycle_exists THEN RAISE EXCEPTION 'ranking supersession cycles are not allowed'; END IF;
 SELECT EXISTS(SELECT 1 FROM rankings successor WHERE successor.supersedes_ranking_id=parent.id AND successor.id<>NEW.id) INTO other_successor; IF other_successor THEN RAISE EXCEPTION 'ranking supersession parent already has a pending or historical successor'; END IF; RETURN NEW; END; $$;
-- Current active official ranking query: terminal chain node (no successor of any status) AND status in VALIDATED/PUBLISHED.
-- A terminal ARCHIVED ranking intentionally yields no active official ranking and never resurrects an ancestor.
