import { transaction, audit, one } from './shared.js';
import type { Actor, RankingInput } from './types.js';

export const rankings = {
  create: (actor: Actor, input: RankingInput) => transaction(async client => { const result = await client.query("insert into rankings(stage_id,occurrence_id,event_id,category_id,regulation_version_id,ranking_type,calculation_version,calculation_metadata,created_by_user_id,supersedes_ranking_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *", [input.stageId, input.occurrenceId ?? null, input.eventId, input.categoryId, input.regulationVersionId, input.rankingType, input.calculationVersion, input.calculationMetadata ?? null, actor.userId, input.supersedesRankingId ?? null]); await audit(client, actor.userId, 'CREATE', 'RANKING', result.rows[0].id); return result.rows[0]; }),
  input: (actor: Actor, id: string, resultId: string, validationId: string) => transaction(async client => { const result = await client.query('insert into ranking_inputs(ranking_id,result_id,result_validation_id) values($1,$2,$3) returning *', [id, resultId, validationId]); await audit(client, actor.userId, 'ADD_INPUT', 'RANKING', id); return result.rows[0]; }),
  removeInput: (actor: Actor, id: string, inputId: string) => transaction(async client => { await one(client, 'delete from ranking_inputs where id=$1 and ranking_id=$2 returning id', [inputId, id]); await audit(client, actor.userId, 'REMOVE_INPUT', 'RANKING', id); }),
  row: (actor: Actor, id: string, entryId: string, position: number, points?: number) => transaction(async client => { const result = await client.query('insert into ranking_rows(ranking_id,competition_entry_id,position,points) values($1,$2,$3,$4) returning *', [id, entryId, position, points ?? null]); await audit(client, actor.userId, 'ADD_ROW', 'RANKING', id); return result.rows[0]; }),
  removeRow: (actor: Actor, id: string, rowId: string) => transaction(async client => { await one(client, 'delete from ranking_rows where id=$1 and ranking_id=$2 returning id', [rowId, id]); await audit(client, actor.userId, 'REMOVE_ROW', 'RANKING', id); }),
  transition: (actor: Actor, id: string, status: 'VALIDATED' | 'PUBLISHED' | 'ARCHIVED') => transaction(async client => { const result = await one(client, 'update rankings set status=$1 where id=$2 returning *', [status, id]); await audit(client, actor.userId, status, 'RANKING', id); return result; }),
  read: (id: string) => transaction(async client => ({ ranking: await one(client, 'select * from rankings where id=$1', [id]), inputs: (await client.query('select * from ranking_inputs where ranking_id=$1 order by input_order', [id])).rows, rows: (await client.query('select * from ranking_rows where ranking_id=$1 order by position', [id])).rows })),
  current: (stageId: string, eventId: string, categoryId: string, type: string) => transaction(async client => (await client.query("select r.* from rankings r where r.stage_id=$1 and r.event_id=$2 and r.category_id=$3 and r.ranking_type=$4 and r.status in ('VALIDATED','PUBLISHED') and not exists(select 1 from rankings s where s.supersedes_ranking_id=r.id and s.status<>'DRAFT')", [stageId, eventId, categoryId, type])).rows[0] ?? null)
};
