import React, { useEffect, useMemo, useState } from 'react';
import { CompetitionApi, CompetitionApiError, type Award, type Competition, type Eligibility, type Entry, type Qualification, type Ranking, type Reference, type Result, dependentSelection, errorMessage } from './api';

type Tab = 'entries' | 'results' | 'qualifications' | 'rankings' | 'awards' | 'eligibility';
type Notice = { text: string; error?: boolean } | null;
const pageSize = 25;
const sensitive = new Set(['reject', 'withdraw', 'void', 'revoke', 'archive', 'publish']);

function Select({ label, value, options, onChange, disabled, required = true }: { label: string; value?: string; options: Array<{ id: string | number; label: string }>; onChange: (value: string) => void; disabled?: boolean; required?: boolean }) {
  return <label>{label}<select aria-label={label} value={value ?? ''} onChange={e => onChange(e.target.value)} disabled={disabled} required={required}><option value="">اختر…</option>{options.map(option => <option key={option.id} value={String(option.id)}>{option.label}</option>)}</select></label>;
}
function Json({ value }: { value: unknown }) { return <pre className="competition-json">{JSON.stringify(value, null, 2)}</pre>; }
function Pager({ total, offset, onChange }: { total?: number; offset: number; onChange: (value: number) => void }) { return <div className="competition-pager"><button disabled={offset === 0} onClick={() => onChange(Math.max(0, offset - pageSize))}>السابق</button><span>عرض {offset + 1}–{Math.min(offset + pageSize, total ?? offset + pageSize)} من {total ?? '…'}</span><button disabled={total === undefined || offset + pageSize >= total} onClick={() => onChange(offset + pageSize)}>التالي</button></div>; }
const statusLabels: Record<string, string> = { DRAFT: 'مسودة', REVIEW: 'قيد المراجعة', APPROVED: 'معتمدة', REGISTRATION: 'التسجيل', ACTIVE: 'نشطة', RESULTS: 'النتائج', CLOSED: 'مغلقة', ARCHIVED: 'مؤرشفة', SUBMITTED: 'مُرسلة', VALIDATED: 'مُتحققة', REJECTED: 'مرفوضة', WITHDRAWN: 'مسحوبة', ISSUED: 'صادرة', REVOKED: 'ملغاة' };
function Status({ value }: { value: string }) { return <span className="competition-status" aria-label={`الحالة ${value}`}>{statusLabels[value] ?? value}</span>; }

export function CompetitionAdmin({ token }: { token: string }) {
  const api = useMemo(() => new CompetitionApi(token), [token]);
  const [tab, setTab] = useState<Tab>('entries'); const [notice, setNotice] = useState<Notice>(null); const [competitions, setCompetitions] = useState<Competition[]>([]); const [selectedCompetition, setSelectedCompetition] = useState('');
  useEffect(() => { api.competitions.list().then(result => { setCompetitions(result.data); setSelectedCompetition(current => current || result.data[0]?.id || ''); }).catch(error => setNotice({ text: errorMessage(error), error: true })); }, [api]);
  const competition = competitions.find(row => row.id === selectedCompetition);
  const tell = async (work: () => Promise<unknown>) => { try { await work(); setNotice({ text: 'تم حفظ التغيير. تم تحديث الحالة من الخادم.' }); } catch (error) { setNotice({ text: errorMessage(error), error: true }); } };
  return <section className="competition-admin" dir="rtl"><div className="competition-head"><div><div className="eyebrow">المنافسات الرسمية</div><h2>إدارة المنافسات</h2><p>كل النتائج والحالات المرجعية تأتي من الخادم المعتمد.</p></div></div><section className="panel competition-overview"><h3>المعلومات الأساسية</h3>{competitions.length === 0 ? <div className="empty">لا توجد منافسات متاحة ضمن الصلاحية الحالية.</div> : <><Select label="المنافسة" value={selectedCompetition} options={competitions.map(row => ({ id: row.id, label: row.name }))} onChange={setSelectedCompetition}/>{competition && <div className="competition-overview-grid"><span><small>الموسم</small><b>{competition.season_name}</b></span><span><small>الحالة</small><Status value={competition.status}/></span><span><small>الفترة</small><b>{competition.start_date ?? '—'} – {competition.end_date ?? '—'}</b></span></div>}</>}</section><nav className="competition-tabs" aria-label="أقسام المنافسات">{([['entries', 'المشاركات'], ['results', 'النتائج'], ['qualifications', 'التأهيلات'], ['rankings', 'الترتيبات'], ['awards', 'الجوائز'], ['eligibility', 'أهلية المراحل']] as [Tab, string][]).map(([key, label]) => <button key={key} className={tab === key ? 'selected' : ''} onClick={() => { setTab(key); setNotice(null); }}>{label}</button>)}</nav>{notice && <div className={`alert ${notice.error ? 'error' : ''}`} role="status">{notice.text}</div>}
    {tab === 'entries' && <Entries api={api} tell={tell} />}{tab === 'results' && <Results api={api} tell={tell} />}{tab === 'qualifications' && <Qualifications api={api} tell={tell} />}{tab === 'rankings' && <Rankings api={api} tell={tell} />}{tab === 'awards' && <Awards api={api} tell={tell} />}{tab === 'eligibility' && <EligibilityAdmin api={api} tell={tell} />}
  </section>;
}

function useCollection<T>(load: (offset: number) => Promise<{ data: T[]; meta?: { pagination?: { total: number } } }>) { const [rows, setRows] = useState<T[]>([]); const [offset, setOffset] = useState(0); const [total, setTotal] = useState<number>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const refresh = () => { setLoading(true); load(offset).then(result => { setRows(result.data); setTotal(result.meta?.pagination?.total); setError(''); }).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)); }; useEffect(refresh, [offset, load]); return { rows, offset, setOffset, total, loading, error, refresh }; }
function CollectionState({ loading, error, empty }: { loading: boolean; error: string; empty: boolean }) { if (loading) return <div className="empty" aria-live="polite">جارٍ التحميل…</div>; if (error) return <div className="alert error">{error}</div>; if (empty) return <div className="empty">لا توجد بيانات ضمن نطاقك الحالي.</div>; return null; }
function GovernedAction({ label, onClick, pending: externallyPending }: { label: string; onClick: () => Promise<void>; pending?: boolean }) { const [pending, setPending] = useState(false); const active = pending || externallyPending; const act = async () => { if (sensitive.has(label) && !window.confirm(`تأكيد إجراء: ${label}`)) return; setPending(true); try { await onClick(); } finally { setPending(false); } }; return <button className="secondary compact" disabled={active} aria-busy={active} onClick={() => void act()}>{active ? 'جارٍ التنفيذ…' : label}</button>; }

function Entries({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) {
  const [filter, setFilter] = useState(''); const load = useMemo(() => (offset: number) => api.entries.list({ limit: pageSize, offset, status: filter || undefined }), [api, filter]); const c = useCollection(load); const [form, setForm] = useState({ type: 'INDIVIDUAL', stage: '', category: '', version: '', institution: '', participant: '', team: '' }); const [stages, setStages] = useState<Reference[]>([]); const [categories, setCategories] = useState<Reference[]>([]); const [versions, setVersions] = useState<Reference[]>([]); const [institutions, setInstitutions] = useState<Reference[]>([]); const [participants, setParticipants] = useState<Reference[]>([]); const [teams, setTeams] = useState<Reference[]>([]); const [pending, setPending] = useState(false);
  useEffect(() => { api.references.stages().then(x => setStages(x.data)).catch(() => setStages([])); api.references.institutions().then(x => setInstitutions(x.data)).catch(() => setInstitutions([])); }, [api]);
  useEffect(() => { if (!form.stage) return; Promise.all([api.references.categories(form.stage), api.references.regulationVersions(form.stage)]).then(([c, v]) => { setCategories(c.data); setVersions(v.data); }); if (form.type === 'TEAM') api.references.teams(form.stage, form.category || undefined).then(x => setTeams(x.data)); }, [api, form.stage, form.category, form.type]);
  useEffect(() => { if (form.institution) api.references.participants({ institution_id: form.institution, limit: 100 }).then(x => setParticipants(x.data)); }, [api, form.institution]);
  const changeStage = (stage: string) => setForm(value => dependentSelection(value, 'stage', stage, ['category', 'version', 'team']));
  const create = async (event: React.FormEvent) => { event.preventDefault(); setPending(true); await tell(async () => { await api.entries.create({ stageId: form.stage, categoryId: form.category, regulationVersionId: form.version, institutionId: form.institution, ...(form.type === 'TEAM' ? { teamId: form.team } : { participantId: form.participant }) }); c.refresh(); }); setPending(false); };
  return <div className="competition-layout"><section className="panel"><h3>إنشاء مشاركة</h3><form className="competition-form" onSubmit={create}><Select label="النوع" value={form.type} options={[{ id: 'INDIVIDUAL', label: 'فردية' }, { id: 'TEAM', label: 'فريق' }]} onChange={type => setForm({ type, stage: '', category: '', version: '', institution: '', participant: '', team: '' })}/><Select label="المرحلة المؤهلة" value={form.stage} options={stages} onChange={changeStage}/><Select label="الفئة" value={form.category} options={categories} onChange={category => setForm({ ...form, category, team: '' })} disabled={!form.stage}/><Select label="نسخة التنظيم" value={form.version} options={versions} onChange={version => setForm({ ...form, version })} disabled={!form.stage}/><Select label="المؤسسة" value={form.institution} options={institutions} onChange={institution => setForm({ ...form, institution, participant: '', team: '' })}/>{form.type === 'TEAM' ? <Select label="الفريق" value={form.team} options={teams} onChange={team => setForm({ ...form, team })} disabled={!form.stage || !form.category}/> : <Select label="المشارك" value={form.participant} options={participants} onChange={participant => setForm({ ...form, participant })} disabled={!form.institution}/>}<button className="primary" disabled={pending}>{pending ? 'جارٍ الإنشاء…' : 'إنشاء مسودة'}</button></form></section><section className="panel"><div className="competition-list-head"><h3>المشاركات</h3><select aria-label="تصفية الحالة" value={filter} onChange={e => { setFilter(e.target.value); c.setOffset(0); }}><option value="">كل الحالات</option>{['DRAFT', 'SUBMITTED', 'VALIDATED', 'REJECTED', 'WITHDRAWN'].map(x => <option key={x}>{x}</option>)}</select></div><CollectionState {...c} empty={!c.rows.length}/>{c.rows.map(row => <article className="competition-row" key={row.id}><div><b>{row.entry_type} · {row.id.slice(0, 8)}</b><small>المؤسسة: {row.institution_id ?? 'تمثيل'}</small></div><Status value={row.status}/><div className="actions">{row.status === 'DRAFT' && <GovernedAction label="submit" onClick={() => tell(async () => { await api.entries.transition(row.id, 'submit'); c.refresh(); })}/>} {row.status === 'SUBMITTED' && <><GovernedAction label="validate" onClick={() => tell(async () => { await api.entries.transition(row.id, 'validate'); c.refresh(); })}/><GovernedAction label="reject" onClick={() => tell(async () => { await api.entries.transition(row.id, 'reject'); c.refresh(); })}/></>}<GovernedAction label="withdraw" onClick={() => tell(async () => { await api.entries.transition(row.id, 'withdraw'); c.refresh(); })}/></div></article>)}<Pager total={c.total} offset={c.offset} onChange={c.setOffset}/></section></div>;
}

function ResultCreate({ api, tell, refresh }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) {
  const [form, setForm] = useState({ stage: '', occurrence: '', event: '', category: '', version: '', entry: '', payload: '{ }' }); const [stages, setStages] = useState<Reference[]>([]); const [occurrences, setOccurrences] = useState<Reference[]>([]); const [events, setEvents] = useState<Reference[]>([]); const [categories, setCategories] = useState<Reference[]>([]); const [versions, setVersions] = useState<Reference[]>([]); const [entries, setEntries] = useState<Entry[]>([]);
  useEffect(() => { api.references.stages().then(x => setStages(x.data)).catch(() => setStages([])); }, [api]);
  useEffect(() => { if (!form.stage) return; Promise.all([api.references.occurrences(form.stage), api.references.events(form.stage), api.references.categories(form.stage), api.references.regulationVersions(form.stage), api.entries.list({ stage_id: form.stage, limit: 100 })]).then(([o, e, c, v, entries]) => { setOccurrences(o.data); setEvents(e.data); setCategories(c.data); setVersions(v.data); setEntries(entries.data); }); }, [api, form.stage]);
  const stage = stages.find(x => x.id === form.stage);
  return <section className="panel"><h3>إنشاء نتيجة محكومة</h3><form className="competition-form" onSubmit={event => { event.preventDefault(); void tell(async () => { const resultData = JSON.parse(form.payload); await api.results.create({ competitionId: stage?.competition_id, stageId: form.stage, occurrenceId: form.occurrence || undefined, eventId: form.event, categoryId: form.category, competitionEntryId: form.entry, regulationVersionId: form.version, resultData }); refresh(); }); }}><Select label="المرحلة المؤهلة" value={form.stage} options={stages} onChange={stage => setForm(dependentSelection(form, 'stage', stage, ['occurrence', 'event', 'category', 'version', 'entry']))}/><Select label="الحدث" value={form.event} options={events} onChange={event => setForm({ ...form, event })} disabled={!form.stage}/><Select label="التكرار" value={form.occurrence} options={occurrences} onChange={occurrence => setForm({ ...form, occurrence })} disabled={!form.stage} required={false}/><Select label="الفئة" value={form.category} options={categories} onChange={category => setForm({ ...form, category })} disabled={!form.stage}/><Select label="النسخة التنظيمية" value={form.version} options={versions} onChange={version => setForm({ ...form, version })} disabled={!form.stage}/><Select label="المشاركة" value={form.entry} options={entries.map(x => ({ id: x.id, label: `${x.entry_type} · ${x.id.slice(0, 8)}` }))} onChange={entry => setForm({ ...form, entry })} disabled={!form.stage}/><label>بيانات النتيجة (JSON آمن)<textarea aria-label="بيانات النتيجة" value={form.payload} onChange={e => setForm({ ...form, payload: e.target.value })}/></label><button className="primary">إنشاء مسودة نتيجة</button></form></section>;
}

function ResultCorrection({ rows, api, tell, refresh }: { rows: Result[]; api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) { const [id, setId] = useState(''); const [reason, setReason] = useState(''); const [payload, setPayload] = useState('{ }'); const selected = rows.find(row => row.id === id); return <section className="panel"><h3>تصحيح نتيجة عبر مراجعة جديدة</h3><form className="competition-form" onSubmit={event => { event.preventDefault(); if (!selected) return; void tell(async () => { await api.results.revise(selected.id, { revisionNo: selected.latest_revision_no + 1, priorSnapshot: selected.official_payload ?? selected.base_payload, newSnapshot: JSON.parse(payload), reason }); refresh(); }); }}><Select label="النتيجة المراد تصحيحها" value={id} options={rows.filter(x => !x.legacy_unresolved).map(x => ({ id: x.id, label: x.id.slice(0, 8) }))} onChange={setId}/><label>سبب التصحيح<input required aria-label="سبب التصحيح" value={reason} onChange={e => setReason(e.target.value)}/></label><label>الحمولة الجديدة (JSON)<textarea aria-label="الحمولة الجديدة" value={payload} onChange={e => setPayload(e.target.value)}/></label><button className="secondary">إنشاء مراجعة</button></form></section>; }

function Results({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) { const load = useMemo(() => (offset: number) => api.results.list({ limit: pageSize, offset }), [api]); const c = useCollection(load); const [selected, setSelected] = useState<Result | null>(null); const [history, setHistory] = useState<{ revisions: unknown[]; validations: unknown[] } | null>(null); const open = async (id: string) => { await tell(async () => { const [result, details] = await Promise.all([api.results.read(id), api.results.history(id)]); setSelected(result.data); setHistory(details.data); }); }; return <><ResultCreate api={api} tell={tell} refresh={c.refresh}/><ResultCorrection rows={c.rows} api={api} tell={tell} refresh={c.refresh}/><div className="competition-layout"><section className="panel"><h3>النتائج ضمن نطاقك</h3><CollectionState {...c} empty={!c.rows.length}/>{c.rows.map(row => <article className="competition-row" key={row.id}><div><button className="link-button" onClick={() => void open(row.id)}>نتيجة {row.id.slice(0, 8)}</button><small>{row.legacy_unresolved ? 'سجل قديم غير محلول' : `المراجعة ${row.latest_revision_no}`}</small></div><Status value={row.governed_status}/><div className="actions">{row.governed_status === 'DRAFT' && <GovernedAction label="submit" onClick={() => tell(async () => { await api.results.submit(row.id); c.refresh(); })}/>} {row.governed_status === 'SUBMITTED' && <><GovernedAction label="validate" onClick={() => tell(async () => { await api.results.decision(row.id, 'validated', { revisionNo: row.latest_revision_no }); c.refresh(); })}/><GovernedAction label="reject" onClick={() => tell(async () => { await api.results.decision(row.id, 'rejected', { revisionNo: row.latest_revision_no }); c.refresh(); })}/><GovernedAction label="void" onClick={() => tell(async () => { await api.results.decision(row.id, 'void', { revisionNo: row.latest_revision_no }); c.refresh(); })}/></>}<GovernedAction label="archive" onClick={() => tell(async () => { await api.results.archive(row.id); c.refresh(); })}/></div></article>)}<Pager total={c.total} offset={c.offset} onChange={c.setOffset}/></section><section className="panel"><h3>تفاصيل النتيجة</h3>{selected ? <><Status value={selected.governed_status}/><h4>القيمة الرسمية</h4>{selected.official_payload !== null ? <Json value={selected.official_payload}/> : <p>لا توجد قيمة رسمية معتمدة بعد.</p>}<h4>البيانات الأساسية</h4><Json value={selected.base_payload}/><h4>القرار الحالي</h4><Json value={selected.current_authoritative_decision}/><h4>السجل</h4><Json value={history}/></> : <div className="empty">اختر نتيجة لعرض القيمة الرسمية والمراجعات.</div>}</section></div></>; }

function QualificationCreate({ api, tell, refresh }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) {
  const [entries, setEntries] = useState<Entry[]>([]); const [stages, setStages] = useState<Reference[]>([]); const [form, setForm] = useState({ source: '', destination: '', version: '', decision: 'RESULT_BASED', reason: '' }); const [versions, setVersions] = useState<Reference[]>([]);
  useEffect(() => { api.entries.list({ limit: 100 }).then(x => setEntries(x.data)); api.references.stages().then(x => setStages(x.data)); }, [api]);
  useEffect(() => { if (form.destination) api.references.regulationVersions(form.destination).then(x => setVersions(x.data)); }, [api, form.destination]);
  const source = entries.find(x => x.id === form.source);
  return <section className="panel"><h3>إنشاء تأهيل</h3><form className="competition-form" onSubmit={event => { event.preventDefault(); if (!source) return; void tell(async () => { await api.qualifications.create({ sourceEntryId: source.id, sourceStageId: source.stage_id, destinationStageId: form.destination, regulationVersionId: form.version, decisionType: form.decision, reason: form.decision === 'MANUAL' ? form.reason : undefined }); refresh(); }); }}><Select label="مشاركة المصدر" value={form.source} options={entries.map(x => ({ id: x.id, label: `${x.entry_type} · ${x.id.slice(0, 8)}` }))} onChange={source => setForm({ ...form, source })}/><Select label="مرحلة الوجهة" value={form.destination} options={stages} onChange={destination => setForm({ ...form, destination, version: '' })}/><Select label="النسخة التنظيمية" value={form.version} options={versions} onChange={version => setForm({ ...form, version })} disabled={!form.destination}/><Select label="نوع القرار" value={form.decision} options={[{ id: 'RESULT_BASED', label: 'مستند إلى نتيجة' }, { id: 'MANUAL', label: 'يدوي' }]} onChange={decision => setForm({ ...form, decision })}/>{form.decision === 'MANUAL' && <label>سبب التأهيل اليدوي<input required aria-label="سبب التأهيل اليدوي" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })}/></label>}<button className="primary">إنشاء مسودة تأهيل</button></form></section>;
}

function Qualifications({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) { const load = useMemo(() => (offset: number) => api.qualifications.list({ limit: pageSize, offset }), [api]); const c = useCollection(load); const [candidates, setCandidates] = useState<Result[]>([]); useEffect(() => { api.results.list({ evidence_candidate: 'true', limit: 100 }).then(x => setCandidates(x.data)); }, [api]); return <><QualificationCreate api={api} tell={tell} refresh={c.refresh}/><section className="panel"><h3>التأهيلات وأدلة النتائج</h3><p>لا يعرض محدد الدليل إلا النتائج ذات قرار VALIDATED حالي.</p><CollectionState {...c} empty={!c.rows.length}/>{c.rows.map(row => <QualificationRow key={row.id} row={row} candidates={candidates} api={api} tell={tell} refresh={c.refresh}/>) }<Pager total={c.total} offset={c.offset} onChange={c.setOffset}/></section></>; }
function QualificationRow({ row, candidates, api, tell, refresh }: { row: Qualification; candidates: Result[]; api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) { const [candidate, setCandidate] = useState(''); return <article className="competition-row qualification-row"><div><b>{row.decision_type} · {row.id.slice(0, 8)}</b><small>{row.reason ?? 'لا يوجد سبب'}</small></div><Status value={row.status}/><div className="actions">{row.status === 'DRAFT' && <><Select label="دليل النتيجة" value={candidate} options={candidates.filter(x => x.current_validation).map(x => ({ id: x.id, label: `${x.id.slice(0, 8)} · ${x.current_validation!.decision}` }))} onChange={setCandidate} required={false}/>{candidate && <GovernedAction label="attach evidence" onClick={() => tell(async () => { const x = candidates.find(value => value.id === candidate)!; await api.qualifications.evidence(row.id, x.id, x.current_validation!.id); refresh(); })}/>}<GovernedAction label="approve" onClick={() => tell(async () => { await api.qualifications.transition(row.id, 'approve'); refresh(); })}/></>}<GovernedAction label="revoke" onClick={() => tell(async () => { await api.qualifications.transition(row.id, 'revoke'); refresh(); })}/><GovernedAction label="archive" onClick={() => tell(async () => { await api.qualifications.transition(row.id, 'archive'); refresh(); })}/></div></article>; }

function RankingCreate({ api, tell, refresh }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) {
  const [form, setForm] = useState({ stage: '', occurrence: '', event: '', category: '', version: '', type: 'EVENT', calculation: 'v1' }); const [stages, setStages] = useState<Reference[]>([]); const [occurrences, setOccurrences] = useState<Reference[]>([]); const [events, setEvents] = useState<Reference[]>([]); const [categories, setCategories] = useState<Reference[]>([]); const [versions, setVersions] = useState<Reference[]>([]);
  useEffect(() => { api.references.stages().then(x => setStages(x.data)); }, [api]); useEffect(() => { if (!form.stage) return; Promise.all([api.references.occurrences(form.stage), api.references.events(form.stage), api.references.categories(form.stage), api.references.regulationVersions(form.stage)]).then(([o,e,c,v]) => { setOccurrences(o.data); setEvents(e.data); setCategories(c.data); setVersions(v.data); }); }, [api, form.stage]);
  return <section className="panel"><h3>إنشاء ترتيب مسودة</h3><form className="competition-form" onSubmit={event => { event.preventDefault(); void tell(async () => { await api.rankings.create({ stageId: form.stage, occurrenceId: form.occurrence || undefined, eventId: form.event, categoryId: form.category, regulationVersionId: form.version, rankingType: form.type, calculationVersion: form.calculation }); refresh(); }); }}><Select label="المرحلة" value={form.stage} options={stages} onChange={stage => setForm(dependentSelection(form, 'stage', stage, ['occurrence','event','category','version']))}/><Select label="الحدث" value={form.event} options={events} onChange={event => setForm({ ...form, event })} disabled={!form.stage}/><Select label="التكرار" value={form.occurrence} options={occurrences} onChange={occurrence => setForm({ ...form, occurrence })} disabled={!form.stage} required={false}/><Select label="الفئة" value={form.category} options={categories} onChange={category => setForm({ ...form, category })} disabled={!form.stage}/><Select label="نسخة التنظيم" value={form.version} options={versions} onChange={version => setForm({ ...form, version })} disabled={!form.stage}/><Select label="نوع الترتيب" value={form.type} options={['EVENT','CATEGORY','STAGE'].map(id => ({ id, label: id }))} onChange={type => setForm({ ...form, type })}/><label>نسخة الحساب<input aria-label="نسخة الحساب" value={form.calculation} onChange={e => setForm({ ...form, calculation: e.target.value })}/></label><button className="primary">إنشاء ترتيب</button></form></section>;
}

function Rankings({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) { const load = useMemo(() => (offset: number) => api.rankings.list({ limit: pageSize, offset }), [api]); const c = useCollection(load); const [candidates, setCandidates] = useState<Result[]>([]); useEffect(() => { api.results.list({ evidence_candidate: 'true', limit: 100 }).then(x => setCandidates(x.data)); }, [api]); return <><RankingCreate api={api} tell={tell} refresh={c.refresh}/><section className="panel"><h3>الترتيبات</h3><p>الحالة الحالية تأتي من مسار الخادم، لا من supersedes_ranking_id.</p><CollectionState {...c} empty={!c.rows.length}/>{c.rows.map(row => <RankingRow key={row.id} row={row} candidates={candidates} api={api} tell={tell} refresh={c.refresh}/>)}<Pager total={c.total} offset={c.offset} onChange={c.setOffset}/></section></>; }
function RankingRow({ row, candidates, api, tell, refresh }: { row: Ranking; candidates: Result[]; api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) { const [candidate, setCandidate] = useState(''); const [entries, setEntries] = useState<Entry[]>([]); const [entry, setEntry] = useState(''); const [position, setPosition] = useState(''); const frozen = row.status !== 'DRAFT'; useEffect(() => { if (!frozen) api.entries.list({ stage_id: row.stage_id, category_id: row.category_id, limit: 100 }).then(x => setEntries(x.data)); }, [api, row.stage_id, row.category_id, frozen]); return <article className="competition-row qualification-row"><div><b>{row.ranking_type} · {row.id.slice(0, 8)}</b><small>{frozen ? 'اللقطة مقفلة للقراءة فقط' : 'مسودة قابلة للتحرير'}</small></div><Status value={row.status}/><div className="actions">{!frozen && <><Select label="مدخل نتيجة معتمدة" value={candidate} options={candidates.filter(x => x.current_validation).map(x => ({ id: x.id, label: x.id.slice(0, 8) }))} onChange={setCandidate} required={false}/>{candidate && <GovernedAction label="add input" onClick={() => tell(async () => { const x = candidates.find(value => value.id === candidate)!; await api.rankings.input(row.id, x.id, x.current_validation!.id); refresh(); })}/>}<Select label="مشاركة صف الترتيب" value={entry} options={entries.map(x => ({ id: x.id, label: `${x.entry_type} · ${x.id.slice(0, 8)}` }))} onChange={setEntry} required={false}/><label>المركز<input aria-label="المركز" type="number" min="1" value={position} onChange={e => setPosition(e.target.value)}/></label>{entry && position && <GovernedAction label="add row" onClick={() => tell(async () => { await api.rankings.row(row.id, { competitionEntryId: entry, position: Number(position) }); refresh(); })}/>}<GovernedAction label="validate" onClick={() => tell(async () => { await api.rankings.transition(row.id, 'validate'); refresh(); })}/></>} {row.status === 'VALIDATED' && <GovernedAction label="publish" onClick={() => tell(async () => { await api.rankings.transition(row.id, 'publish'); refresh(); })}/>}<GovernedAction label="archive" onClick={() => tell(async () => { await api.rankings.transition(row.id, 'archive'); refresh(); })}/></div></article>; }

function AwardCreate({ api, tell, refresh }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void>; refresh: () => void }) {
  const [rankings, setRankings] = useState<Ranking[]>([]); const [entries, setEntries] = useState<Entry[]>([]); const [form, setForm] = useState({ ranking: '', entry: '', type: 'MEDAL', label: '' });
  useEffect(() => { api.rankings.list({ limit: 100 }).then(x => setRankings(x.data)); api.entries.list({ limit: 100 }).then(x => setEntries(x.data)); }, [api]); const ranking = rankings.find(x => x.id === form.ranking);
  return <section className="panel"><h3>إنشاء جائزة مسودة</h3><form className="competition-form" onSubmit={event => { event.preventDefault(); if (!ranking) return; void tell(async () => { await api.awards.create({ rankingId: ranking.id, competitionEntryId: form.entry, awardType: form.type, label: form.label || undefined, regulationVersionId: ranking.regulation_version_id }); refresh(); }); }}><Select label="الترتيب المصدر" value={form.ranking} options={rankings.map(x => ({ id: x.id, label: `${x.ranking_type} · ${x.id.slice(0, 8)}` }))} onChange={ranking => setForm({ ...form, ranking, entry: '' })}/><Select label="المستفيد" value={form.entry} options={entries.filter(x => !ranking || x.stage_id === ranking.stage_id).map(x => ({ id: x.id, label: `${x.entry_type} · ${x.id.slice(0, 8)}` }))} onChange={entry => setForm({ ...form, entry })} disabled={!form.ranking}/><Select label="نوع الجائزة" value={form.type} options={['MEDAL','TITLE','TROPHY','CERTIFICATE','OTHER'].map(id => ({ id, label: id }))} onChange={type => setForm({ ...form, type })}/><label>التسمية<input aria-label="تسمية الجائزة" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })}/></label><button className="primary">إنشاء جائزة</button></form></section>;
}

function Awards({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) { const load = useMemo(() => (offset: number) => api.awards.list({ limit: pageSize, offset }), [api]); const c = useCollection(load); return <><AwardCreate api={api} tell={tell} refresh={c.refresh}/><section className="panel"><h3>الجوائز</h3><CollectionState {...c} empty={!c.rows.length}/>{c.rows.map(row => <article className="competition-row" key={row.id}><div><b>{row.award_type} · {row.label ?? '—'}</b><small>{row.status === 'ISSUED' || row.status === 'REVOKED' ? `الإصدار: ${row.issued_at ?? '—'} · الجهة: ${row.issued_by_user_id ?? '—'}` : 'مسودة'}</small>{row.revoked_at && <small>الإلغاء: {row.revoked_at} · {row.revoked_by_user_id}</small>}</div><Status value={row.status}/><div className="actions">{row.status === 'DRAFT' && <GovernedAction label="issue" onClick={() => tell(async () => { await api.awards.transition(row.id, 'issue'); c.refresh(); })}/>} {row.status === 'ISSUED' && <GovernedAction label="revoke" onClick={() => tell(async () => { await api.awards.transition(row.id, 'revoke'); c.refresh(); })}/>}<GovernedAction label="archive" onClick={() => tell(async () => { await api.awards.transition(row.id, 'archive'); c.refresh(); })}/></div></article>)}<Pager total={c.total} offset={c.offset} onChange={c.setOffset}/></section></>; }

function EligibilityAdmin({ api, tell }: { api: CompetitionApi; tell: (work: () => Promise<unknown>) => Promise<void> }) { const [stages, setStages] = useState<Reference[]>([]); const [stage, setStage] = useState(''); const [kind, setKind] = useState<'ORGANIZATION' | 'DAIRA' | 'INSTITUTION'>('ORGANIZATION'); const [organizations, setOrganizations] = useState<Reference[]>([]); const [dairas, setDairas] = useState<Array<{ id: number; label: string }>>([]); const [institutions, setInstitutions] = useState<Reference[]>([]); const [target, setTarget] = useState(''); const [grants, setGrants] = useState<Eligibility[]>([]); const [available, setAvailable] = useState<boolean>();
  useEffect(() => { api.references.stages().then(x => setStages(x.data)); api.references.organizations().then(x => { setOrganizations(x.data); setAvailable(true); }).catch(error => { if (error instanceof CompetitionApiError && error.code === 'FORBIDDEN') setAvailable(false); }); api.references.dairas().then(x => setDairas(x.data)).catch(() => {}); api.references.institutions().then(x => setInstitutions(x.data)).catch(() => {}); }, [api]);
  useEffect(() => { if (stage && available) api.eligibility.list(stage).then(x => setGrants(x.data)); }, [api, stage, available]);
  if (available === false) return <section className="panel"><h3>أهلية المراحل</h3><div className="empty">إعداد الأهلية متاح فقط للنطاق الوطني المصرح له.</div></section>;
  const options = kind === 'ORGANIZATION' ? organizations : kind === 'DAIRA' ? dairas : institutions;
  return <section className="panel"><h3>أهلية المرحلة</h3><p>الأهلية ليست جغرافية الاستضافة، وتُدار للمراحل DRAFT فقط.</p><form className="competition-form" onSubmit={event => { event.preventDefault(); void tell(async () => { await api.eligibility.add(stage, kind === 'ORGANIZATION' ? { scopeType: kind, organizationId: target } : kind === 'DAIRA' ? { scopeType: kind, dairaId: Number(target) } : { scopeType: kind, institutionId: target }); const response = await api.eligibility.list(stage); setGrants(response.data); }); }}><Select label="المرحلة" value={stage} options={stages} onChange={value => { setStage(value); setTarget(''); }}/><Select label="نوع النطاق" value={kind} options={['ORGANIZATION', 'DAIRA', 'INSTITUTION'].map(id => ({ id, label: id }))} onChange={value => { setKind(value as typeof kind); setTarget(''); }}/><Select label="الهدف المؤهل" value={target} options={options} onChange={setTarget} disabled={!stage}/><button className="primary" disabled={!stage || !target}>إضافة أهلية</button></form><div className="competition-grants">{grants.map(grant => <article key={grant.id} className="competition-row"><span>{grant.scope_type}</span><small>{grant.organization_id ?? grant.daira_id ?? grant.institution_id}</small><GovernedAction label="remove grant" onClick={() => tell(async () => { await api.eligibility.remove(stage, grant.id); setGrants(value => value.filter(row => row.id !== grant.id)); })}/></article>)}</div></section>; }
