import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, CheckCircle2, FileCheck2, LayoutDashboard, QrCode, Search, ShieldCheck, Trophy, Users } from 'lucide-react';
import { RoleAdmin } from './RoleAdmin';
import { PublicAwards, PublicRecords, PublicResults } from './public-portal';
import './styles.css';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';
type View = 'home' | 'seasons' | 'competitions' | 'results' | 'awards' | 'records' | 'verify' | 'admin';

function App() { const [view, setView] = useState<View>('home'); const [reference, setReference] = useState(''); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); async function verify(event: React.FormEvent) { event.preventDefault(); setError(''); setResult(null); try { const response = await fetch(`${API}/api/v1/public/licenses/verify/${encodeURIComponent(reference)}`); if (!response.ok) throw new Error('لم يتم العثور على ترخيص مطابق'); setResult(await response.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر الاتصال بالخادم'); } } const nav = [['home', 'الرئيسية'], ['seasons', 'المواسم'], ['competitions', 'المنافسات'], ['results', 'النتائج الرسمية'], ['awards', 'الجوائز'], ['records', 'الأرقام / السجلات الرسمية'], ['verify', 'تحقق من الترخيص']] as const; return <div dir="rtl" className="app"><header className="topbar"><div className="brand" onClick={() => setView('home')}><span className="brand-mark">ن</span><span><b>NSSMS</b><small>النظام الوطني للرياضة المدرسية</small></span></div><nav>{nav.map(([key, label]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)}>{label}</button>)}</nav><button className="admin-link" onClick={() => setView('admin')}><LayoutDashboard size={16} /> البوابة الإدارية</button></header><main>{view === 'home' && <Home onVerify={() => setView('verify')} onAdmin={() => setView('admin')} />}{view === 'seasons' && <Listing title="المواسم الرياضية" endpoint="seasons" icon={<Activity />} />}{view === 'competitions' && <Listing title="المنافسات" endpoint="competitions" icon={<Trophy />} />}{view === 'results' && <PublicResults />}{view === 'awards' && <PublicAwards />}{view === 'records' && <PublicRecords />}{view === 'verify' && <section className="verify-page"><div className="eyebrow"><QrCode size={18} /> خدمة عامة</div><h1>تحقق من الترخيص الرياضي</h1><p>أدخل مرجع التحقق لعرض المعلومات العامة المعتمدة فقط.</p><form onSubmit={verify} className="verify-form"><input value={reference} onChange={event => setReference(event.target.value)} minLength={20} required placeholder="مرجع التحقق" /><button className="primary"><Search size={18} /> تحقق الآن</button></form>{error && <div className="alert error">{error}</div>}{result && <div className="result-card"><CheckCircle2 size={30} /><div><strong>تم التحقق من الترخيص</strong><span>الحالة: {result.status}</span>{result.issuedAt && <small>تاريخ الإصدار: {new Date(result.issuedAt).toLocaleDateString('ar-DZ')}</small>}{result.expiresAt && <small>تاريخ الانتهاء: {new Date(result.expiresAt).toLocaleDateString('ar-DZ')}</small>}</div></div>}</section>}{view === 'admin' && <RoleAdmin onBack={() => setView('home')} />}</main><footer><span>© NSSMS — منصة تجريبية محلية</span><span>الخصوصية والأمان · المساعدة</span></footer></div>; }
function Home({ onVerify, onAdmin }: { onVerify: () => void; onAdmin: () => void }) { return <><section className="hero"><div><div className="eyebrow"><ShieldCheck size={18} /> منصة وطنية رقمية</div><h1>إدارة الرياضة المدرسية<br /><em>بثقة وشفافية</em></h1><p>منصة موحدة لإدارة المواسم والمنافسات والتراخيص الرياضية مع حفظ السجل التاريخي وإتاحة التحقق العام.</p><div className="hero-actions"><button className="primary" onClick={onVerify}><QrCode size={18} /> تحقق من ترخيص</button><button className="secondary" onClick={onAdmin}>دخول الإدارة</button></div></div><div className="hero-visual"><div className="seal">ن<br /><small>NSSMS</small></div></div></section><section className="stats"><Stat icon={<Trophy />} number="12" label="موسمًا رياضيًا" /><Stat icon={<Users />} number="—" label="مؤسسة تعليمية" /><Stat icon={<FileCheck2 />} number="—" label="ترخيصًا رقميًا" /></section></>; }
function Stat({ icon, number, label }: { icon: React.ReactNode; number: string; label: string }) { return <div className="stat"><span>{icon}</span><div><b>{number}</b><small>{label}</small></div></div>; }
function Listing({ title, endpoint, icon }: { title: string; endpoint: string; icon: React.ReactNode }) { const [rows, setRows] = useState<any[]>([]); useEffect(() => { fetch(`${API}/api/v1/public/${endpoint}`).then(response => response.ok ? response.json() : { data: [] }).then(data => setRows(data.data ?? [])).catch(() => setRows([])); }, [endpoint]); return <section className="listing"><div className="eyebrow">{icon} السجل العام</div><h1>{title}</h1><div className="cards">{rows.map((row, index) => <article className="item-card" key={row.id ?? index}><div className="icon-box">{icon}</div><div><h3>{row.name ?? row.competition_name ?? 'نتيجة منشورة'}</h3><p>معلومات منشورة ومعتمدة من الإدارة المختصة</p></div><span className="badge">{row.status ?? 'منشور'}</span></article>)}</div></section>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
