import { BarChart3, Medal, Trophy } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { publicApi, type PublicAward, type PublicRecord, type PublicResult } from './public-api';

const awardTypes: Record<string, string> = { MEDAL: 'ميدالية', TITLE: 'لقب', TROPHY: 'كأس', CERTIFICATE: 'شهادة', OTHER: 'جائزة' };
const rankingTypes: Record<string, string> = { EVENT: 'رقم الحدث', CATEGORY: 'رقم الفئة', STAGE: 'رقم المرحلة' };
const date = (value: string | null) => value ? new Date(value).toLocaleDateString('ar-DZ') : '—';
function PublicCollection<T>({ title, eyebrow, icon, load, emptyText, children }: { title: string; eyebrow: string; icon: ReactNode; load: () => Promise<{ data: T[] }>; emptyText: string; children: (row: T) => ReactNode }) { const [rows, setRows] = useState<T[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); useEffect(() => { let current = true; setState('loading'); load().then(result => { if (current) { setRows(result.data); setState('ready'); } }).catch(() => { if (current) setState('error'); }); return () => { current = false; }; }, [load]); return <section className="listing public-listing"><div className="eyebrow">{icon} {eyebrow}</div><h1>{title}</h1>{state === 'loading' && <div className="empty" role="status">جارٍ تحميل البيانات الرسمية…</div>}{state === 'error' && <div className="alert error" role="alert">تعذر تحميل البيانات العامة حالياً. حاول مرة أخرى لاحقاً.</div>}{state === 'ready' && !rows.length && <div className="empty">{emptyText}</div>}{state === 'ready' && rows.length > 0 && <div className="public-cards">{rows.map((row, index) => <article className="public-card" key={index}>{children(row)}</article>)}</div>}</section>; }
export function PublicResults() { return <PublicCollection title="النتائج الرسمية" eyebrow="السجل العام" icon={<BarChart3 size={18} />} load={publicApi.results} emptyText="لا توجد نتائج رسمية منشورة حالياً.">{(row: PublicResult) => <><div className="public-card-head"><h3>{row.competition_name}</h3><span className="badge">رسمي</span></div><p>{row.season_name} · {row.event_name} · {row.category_name}</p><p>{row.competitor_name ?? 'المشارك غير محدد'} · {row.entry_type === 'TEAM' ? 'فريق' : 'فردي'}</p><div className="public-card-meta"><span>{row.position === null ? 'الترتيب —' : `الترتيب ${row.position}`}</span><span>{row.points === null ? 'النقاط —' : `${row.points} نقطة`}</span><small>النشر: {date(row.published_at)}</small></div></>}</PublicCollection>; }
export function PublicAwards() { return <PublicCollection title="الجوائز" eyebrow="الجوائز الرسمية" icon={<Trophy size={18} />} load={publicApi.awards} emptyText="لا توجد جوائز صادرة رسمياً حالياً.">{(row: PublicAward) => <><div className="public-card-head"><h3>{row.label ?? awardTypes[row.award_type] ?? 'جائزة رسمية'}</h3><span className="badge">صادرة</span></div><p>{awardTypes[row.award_type] ?? row.award_type} · {row.competition_name} · {row.season_name}</p><p>{row.competitor_name ?? 'المستفيد غير محدد'}{row.event_name ? ` · ${row.event_name}` : ''}{row.category_name ? ` · ${row.category_name}` : ''}</p><div className="public-card-meta"><span>{row.ranking_type ? rankingTypes[row.ranking_type] ?? row.ranking_type : 'جائزة رسمية'}</span><small>تاريخ الإصدار: {date(row.issued_at)}</small></div></>}</PublicCollection>; }
export function PublicRecords() { return <PublicCollection title="الأرقام / السجلات الرسمية" eyebrow="السجلات الرسمية" icon={<Medal size={18} />} load={publicApi.records} emptyText="لا توجد سجلات رسمية معترف بها حالياً.">{(row: PublicRecord) => <><div className="public-card-head"><h3>{rankingTypes[row.ranking_type] ?? 'سجل رسمي'}</h3><span className="badge">{row.status === 'PUBLISHED' ? 'منشور' : 'معتمد'}</span></div><p>{row.competition_name} · {row.season_name}</p><p>{row.event_name ?? 'الحدث غير محدد'}{row.category_name ? ` · ${row.category_name}` : ''}</p><div className="public-card-meta"><span>المرحلة: {row.stage_level_code}</span><small>تاريخ الاعتراف: {date(row.recognized_at)}</small></div></>}</PublicCollection>; }
