import React, { useEffect, useState } from 'react';
import { LayoutDashboard, ShieldCheck } from 'lucide-react';
import { CompetitionAdmin } from './competition/CompetitionAdmin';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';
const labels: Record<string, string> = { SYSTEM_ADMINISTRATOR: 'إداري عام', NATIONAL_ADMINISTRATOR: 'إداري وطني', ASSOCIATION_ADMINISTRATOR: 'مدير رابطة', ASSOCIATION_REPRESENTATIVE: 'ممثل رابطة', DAIRA_OFFICER: 'مسؤول دائرة', MEMBER_INSTITUTION_USER: 'مسؤول مؤسسة' };

export function RoleAdmin({ onBack }: { onBack: () => void }) {
  const [user, setUser] = useState<any>(null); const [username, setUsername] = useState('demo.admin'); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const token = localStorage.getItem('nssms_token'); if (token) fetch(`${API}/api/v1/auth/me`, { headers: { authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : Promise.reject()).then(value => setUser(value.user)).catch(() => localStorage.removeItem('nssms_token')); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch(`${API}/api/v1/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username, password }) }); if (!response.ok) { setError('بيانات الدخول غير صحيحة.'); return; } const data = await response.json(); localStorage.setItem('nssms_token', data.token); setUser(data.user); }
  if (!user) return <section className="login-page" dir="rtl"><button className="back" onClick={onBack}>العودة للبوابة العامة</button><div className="login-card"><div className="brand-mark">ن</div><div className="eyebrow"><ShieldCheck size={18}/> وصول محمي</div><h1>تسجيل الدخول</h1><form onSubmit={submit}><label>اسم المستخدم<input value={username} onChange={event => setUsername(event.target.value)} required/></label><label>كلمة المرور<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={12} required/></label>{error && <div className="alert error">{error}</div>}<button className="primary">دخول الإدارة</button></form></div></section>;
  const token = localStorage.getItem('nssms_token') ?? '';
  return <section className="admin" dir="rtl"><button className="back" onClick={onBack}>العودة</button><div className="admin-head"><div><div className="eyebrow"><LayoutDashboard size={18}/> لوحة الإدارة</div><h1>مرحباً، {user.username}</h1><p>{user.roles?.map((role: string) => labels[role] ?? role).join(' · ')}</p></div></div><ScopedDashboard token={token} roles={user.roles ?? []}/><CompetitionAdmin token={token}/></section>;
}

function ScopedDashboard({ token, roles }: { token: string; roles: string[] }) { const [result, setResult] = useState<any>(null); useEffect(() => { fetch(`${API}/api/v1/dashboard/summary`, { headers: { authorization: `Bearer ${token}` } }).then(response => response.ok ? response.json() : Promise.reject()).then(setResult).catch(() => setResult({ error: 'تعذر تحميل الملخص' })); }, [token]); if (!result) return <div className="empty">جارٍ تحميل لوحة المستخدم…</div>; if (result.error) return <div className="alert error">{result.error}</div>; return <div className="workspace"><div className="workspace-summary">{Object.entries(result.data ?? {}).map(([key, value]) => <div className="summary-card" key={key}><small>{key}</small><b>{String(value)}</b></div>)}</div><div className="panel"><h3>نطاق الوصول</h3><p>{result.scope === 'national' ? 'النطاق الوطني الكامل' : result.scope === 'organization' ? 'نطاق الرابطة' : result.scope === 'daira' ? 'نطاق الدائرة' : 'نطاق المؤسسة'}</p><small>{roles.map(role => labels[role] ?? role).join(' · ')}</small></div></div>; }
