import React, { useEffect, useState } from 'react';
import { LayoutDashboard, ShieldCheck } from 'lucide-react';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';
const labels: Record<string, string> = { SYSTEM_ADMINISTRATOR: 'إداري عام', NATIONAL_ADMINISTRATOR: 'إداري وطني', ASSOCIATION_ADMINISTRATOR: 'مدير رابطة ولائية', ASSOCIATION_REPRESENTATIVE: 'ممثل الرابطة', MEMBER_INSTITUTION_USER: 'مسؤول مؤسسة منخرطة' };

export function RoleAdmin({ onBack }: { onBack: () => void }) {
  const [user, setUser] = useState<any>(null); const [username, setUsername] = useState('demo.admin'); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const token = localStorage.getItem('nssms_token'); if (token) fetch(`${API}/api/v1/auth/me`, { headers: { authorization: `Bearer ${token}` } }).then((r) => r.ok ? r.json() : Promise.reject()).then((d) => setUser(d.user)).catch(() => localStorage.removeItem('nssms_token')); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); const response = await fetch(`${API}/api/v1/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username, password }) }); if (!response.ok) { setError('بيانات الدخول غير صحيحة'); return; } const data = await response.json(); localStorage.setItem('nssms_token', data.token); setUser(data.user); }
  if (!user) return <section className="login-page"><button className="back" onClick={onBack}>← العودة للبوابة العامة</button><div className="login-card"><div className="brand-mark">ن</div><div className="eyebrow"><ShieldCheck size={18} /> وصول حسب الصلاحية</div><h1>تسجيل الدخول</h1><form onSubmit={submit}><label>اسم المستخدم<input value={username} onChange={(e) => setUsername(e.target.value)} required /></label><label>كلمة المرور<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={12} required /></label>{error && <div className="alert error">{error}</div>}<button className="primary">دخول إلى لوحة التحكم</button></form></div></section>;
  return <section className="admin"><button className="back" onClick={onBack}>← العودة</button><div className="admin-head"><div><div className="eyebrow"><LayoutDashboard size={18} /> لوحة المستخدم</div><h1>مرحبًا، {user.username}</h1><p>{user.roles?.map((role: string) => labels[role] ?? role).join(' · ')}</p></div></div><ScopedDashboard token={localStorage.getItem('nssms_token') ?? ''} roles={user.roles ?? []} /></section>;
}

function ScopedDashboard({ token, roles }: { token: string; roles: string[] }) { const [result, setResult] = useState<any>(null); useEffect(() => { fetch(`${API}/api/v1/dashboard/summary`, { headers: { authorization: `Bearer ${token}` } }).then((r) => r.ok ? r.json() : Promise.reject()).then(setResult).catch(() => setResult({ error: 'تعذر تحميل الملخص' })); }, [token]); if (!result) return <div className="empty">جارٍ تحميل لوحة المستخدم…</div>; if (result.error) return <div className="alert error">{result.error}</div>; return <div className="workspace"><div className="workspace-summary">{Object.entries(result.data ?? {}).map(([key, value]) => <div className="summary-card" key={key}><small>{key}</small><b>{String(value)}</b></div>)}</div><div className="panel"><h3>نطاق الوصول</h3><p>{result.scope === 'national' ? 'النطاق الوطني الكامل' : result.scope === 'organization' ? 'بيانات الرابطة المرتبطة بالحساب' : 'بيانات المؤسسة المنخرطة المرتبطة بالحساب'}</p><small>{roles.map((role) => labels[role] ?? role).join(' · ')}</small></div></div>; }
