import { describe, expect, it, vi } from 'vitest';
import { UserAdminApi, UserAdminApiError, roleLabels } from './user-admin-api';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
describe('user administration API contracts', () => {
  it('loads scoped administration data with auth and filters', async () => { const fetcher = vi.fn().mockResolvedValue(response({ data: [], page: 1, pageSize: 50 })); await new UserAdminApi('secret-token', fetcher as unknown as typeof fetch).listUsers({ search: 'ali', status: 'ACTIVE' }); expect(fetcher.mock.calls[0][0]).toContain('/api/v1/admin/users?search=ali&status=ACTIVE'); expect(fetcher.mock.calls[0][1].headers.authorization).toBe('Bearer secret-token'); });
  it('creates users without exposing or persisting credentials', async () => { const fetcher = vi.fn().mockResolvedValue(response({ data: { id: 'u1', username: 'new.user', status: 'ACTIVE', roles: ['DAIRA_OFFICER'] } }, 201)); const body = { username: 'new.user', displayName: 'مستخدم', password: 'A-very-long-password', roleIds: ['r1'] }; await new UserAdminApi('token', fetcher as unknown as typeof fetch).createUser(body); expect(fetcher.mock.calls[0][1].body).toContain('roleIds'); expect(fetcher.mock.calls[0][1].body).toContain('password'); });
  it('uses existing role and status operations', async () => { const fetcher = vi.fn().mockResolvedValue(response({ success: true })); const api = new UserAdminApi('token', fetcher as unknown as typeof fetch); await api.updateRoles('u1', ['r1']); await api.updateStatus('u1', 'DISABLED'); expect(fetcher.mock.calls[0][0]).toContain('/api/v1/admin/users/u1/roles'); expect(fetcher.mock.calls[1][0]).toContain('/api/v1/admin/users/u1/status'); });
  it('loads scope options from existing reference endpoints', async () => { const fetcher = vi.fn().mockResolvedValue(response({ data: [{ id: 'org-1', label: 'رابطة' }] })); const api = new UserAdminApi('token', fetcher as unknown as typeof fetch); await api.listScopes('ASSOCIATION'); expect(fetcher.mock.calls[0][0]).toContain('/api/v1/admin/competition-reference/organizations'); });
  it('updates roles and scope through the atomic access endpoint', async () => { const fetcher = vi.fn().mockResolvedValue(response({ data: { userId: 'u1', scopeType: 'DAIRA', scopeId: '7', scopeName: 'دائرة' } })); const api = new UserAdminApi('token', fetcher as unknown as typeof fetch); await api.updateAccess('u1', ['r1'], 'DAIRA', '7'); expect(fetcher.mock.calls[0][0]).toContain('/api/v1/admin/users/u1/access'); expect(fetcher.mock.calls[0][1].body).toBe(JSON.stringify({ roleIds: ['r1'], scopeType: 'DAIRA', scopeId: '7' })); });
  it('maps backend errors to a stable typed error', async () => { await expect(new UserAdminApi('token', vi.fn().mockResolvedValue(response({ error: 'forbidden' }, 403)) as unknown as typeof fetch).listRoles()).rejects.toBeInstanceOf(UserAdminApiError); });
  it('keeps role labels Arabic and exposes only approved account operations', () => { expect(roleLabels.MEMBER_INSTITUTION_USER).toBe('مسؤول مؤسسة'); expect(UserAdminApi.prototype).not.toHaveProperty('updateScope'); expect(UserAdminApi.prototype).toHaveProperty('resetPassword'); expect(UserAdminApi.prototype).toHaveProperty('updateProfile'); });
});
