import React, { useEffect, useMemo, useState } from 'react';
import { Plus, RefreshCw, Save, UserCog } from 'lucide-react';
import { UserAdminApi, roleLabels, statusLabels, userAdminError, type AdminRole, type AdminUser, type ScopeType } from './user-admin-api';

const blank = { username: '', email: '', displayName: '', password: '', confirmPassword: '', roleIds: [] as string[], scopeType: null as ScopeType | null, scopeId: '' };
export function UserAdmin({ token }: { token: string }) {
  const api = useMemo(() => new UserAdminApi(token), [token]); const [users, setUsers] = useState<AdminUser[]>([]); const [roles, setRoles] = useState<AdminRole[]>([]); const [scopeOptions, setScopeOptions] = useState<Array<{ id: string | number; label: string }>>([]); const [form, setForm] = useState(blank); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminUser | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function load() { setLoading(true); setError(''); try { const [u, r] = await Promise.all([api.listUsers({ search, status }), api.listRoles()]); setUsers(u.data); setRoles(r.data); } catch (cause) { setError(userAdminError(cause)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [api]);
  const setField = (key: keyof typeof blank, value: string) => setForm(current => ({ ...current, [key]: value })); const toggleRole = (id: string) => setForm(current => ({ ...current, roleIds: current.roleIds.includes(id) ? current.roleIds.filter(value => value !== id) : [...current.roleIds, id] })); const selectedScopeType = useMemo<ScopeType | null>(() => { const names = roles.filter(role => form.roleIds.includes(role.id)).map(role => role.name); if (names.some(name => ['SYSTEM_ADMINISTRATOR', 'NATIONAL_ADMINISTRATOR'].includes(name))) return 'NATIONAL'; if (names.some(name => ['ASSOCIATION_ADMINISTRATOR', 'ASSOCIATION_REPRESENTATIVE'].includes(name))) return 'ASSOCIATION'; if (names.includes('DAIRA_OFFICER')) return 'DAIRA'; if (names.includes('MEMBER_INSTITUTION_USER')) return 'INSTITUTION'; return null; }, [roles, form.roleIds]);
  useEffect(() => { if (!selectedScopeType || selectedScopeType === 'NATIONAL') { setScopeOptions([]); return; } void api.listScopes(selectedScopeType).then(result => setScopeOptions(result.data)).catch(cause => setError(userAdminError(cause))); }, [api, selectedScopeType]);
  async function create(event: React.FormEvent) { event.preventDefault(); setError(''); if (form.password !== form.confirmPassword) return setError('تأكيد كلمة المرور غير مطابق.'); if (!form.roleIds.length) return setError('اختر دوراً واحداً على الأقل.'); if (selectedScopeType && selectedScopeType !== 'NATIONAL' && !form.scopeId) return setError('اختر نطاقاً متوافقاً مع الدور.'); setSaving(true); try { const created = await api.createUser({ username: form.username.trim(), displayName: form.displayName.trim(), email: form.email.trim() || undefined, password: form.password, roleIds: form.roleIds }); await api.updateAccess(created.data.id, form.roleIds, selectedScopeType, selectedScopeType === 'NATIONAL' ? null : form.scopeId || null); setForm(blank); setOpen(false); setNotice('تم إنشاء المستخدم بنجاح.'); await load(); } catch (cause) { setError(userAdminError(cause)); } finally { setSaving(false); } }
  async function updateRoles() { if (!editing || !form.roleIds.length) return setError('يجب اختيار دور واحد على الأقل.'); if (selectedScopeType && selectedScopeType !== 'NATIONAL' && !form.scopeId) return setError('اختر نطاقاً متوافقاً مع الدور.'); if (form.password && form.password !== form.confirmPassword) return setError('تأكيد كلمة المرور غير مطابق.'); setSaving(true); try { await api.updateAccess(editing.id, form.roleIds, selectedScopeType, selectedScopeType === 'NATIONAL' ? null : form.scopeId || null); await api.updateProfile(editing.id, form.displayName.trim()); if (form.password) await api.resetPassword(editing.id, form.password); setEditing(null); setForm(blank); setNotice('تم تحديث بيانات الحساب.'); await load(); } catch (cause) { setError(userAdminError(cause)); } finally { setSaving(false); } }
  async function changeStatus(user: AdminUser) { const next = user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'; if (!window.confirm(next === 'DISABLED' ? 'تعطيل هذا الحساب؟' : 'تفعيل هذا الحساب؟')) return; try { await api.updateStatus(user.id, next); setNotice('تم تحديث حالة الحساب.'); await load(); } catch (cause) { setError(userAdminError(cause)); } }
  const formOpen = open || Boolean(editing);
  return <section className="user-admin panel"><div className="user-admin-head"><div><h2><UserCog size={20}/> إدارة المستخدمين والأدوار</h2><p>صلاحية هذه العمليات محصورة بمسؤول النظام. لا تُعرض كلمات المرور أو الرموز.</p></div><button className="primary compact" onClick={() => { setOpen(value => !value); setEditing(null); setForm(blank); }}><Plus size={15}/> مستخدم جديد</button></div>{error && <div className="alert error" role="alert">{error}</div>}{notice && <div className="alert success" role="status">{notice}</div>}
    {formOpen && <form className="user-form" onSubmit={editing ? event => { event.preventDefault(); void updateRoles(); } : create}><h3>{editing ? `تعديل حساب: ${editing.username}` : 'إنشاء مستخدم'}</h3>{!editing && <><label>اسم المستخدم<input value={form.username} onChange={e => setField('username', e.target.value)} minLength={3} maxLength={100} required /></label><label>الاسم الظاهر<input value={form.displayName} onChange={e => setField('displayName', e.target.value)} minLength={2} maxLength={200} required /></label><label>البريد الإلكتروني<input type="email" value={form.email} onChange={e => setField('email', e.target.value)} /></label><label>كلمة المرور<input type="password" value={form.password} onChange={e => setField('password', e.target.value)} minLength={12} maxLength={200} autoComplete="new-password" required /></label><label>تأكيد كلمة المرور<input type="password" value={form.confirmPassword} onChange={e => setField('confirmPassword', e.target.value)} minLength={12} maxLength={200} autoComplete="new-password" required /></label></>} {editing && <><label>الاسم الظاهر<input value={form.displayName} onChange={e => setField('displayName', e.target.value)} minLength={2} maxLength={200} required /></label><label>كلمة مرور جديدة (اختياري)<input type="password" value={form.password} onChange={e => setField('password', e.target.value)} minLength={12} maxLength={200} autoComplete="new-password" /></label><label>تأكيد كلمة المرور الجديدة<input type="password" value={form.confirmPassword} onChange={e => setField('confirmPassword', e.target.value)} minLength={12} maxLength={200} autoComplete="new-password" /></label></>}<fieldset><legend>الأدوار</legend>{roles.map(role => <label className="role-option" key={role.id}><input type="checkbox" checked={form.roleIds.includes(role.id)} onChange={() => toggleRole(role.id)} />{roleLabels[role.name] ?? role.name}</label>)}</fieldset>{selectedScopeType && <label>النطاق {selectedScopeType === 'NATIONAL' ? <input value="النطاق الوطني" readOnly /> : <select value={form.scopeId} onChange={e => setField('scopeId', e.target.value)} required><option value="">اختر النطاق</option>{scopeOptions.map(option => <option key={String(option.id)} value={String(option.id)}>{option.label}</option>)}</select>}</label>}<div className="actions"><button className="primary compact" disabled={saving}><Save size={14}/> حفظ</button><button type="button" className="secondary compact" onClick={() => { setOpen(false); setEditing(null); setForm(blank); }}>إلغاء</button></div></form>}
    <div className="scope-unavailable"><b>إسناد النطاقات</b><span>يتم تحميل النطاقات المسموح بها من الخادم والتحقق منها خادميًا؛ لا توجد معرفات ثابتة في الواجهة.</span></div><div className="user-toolbar"><input placeholder="بحث بالاسم أو الحساب أو البريد" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void load(); }} /><select aria-label="تصفية حسب الحالة" value={status} onChange={e => { const value = e.target.value; setStatus(value); void api.listUsers({ search, status: value }).then(result => setUsers(result.data)).catch(cause => setError(userAdminError(cause))); }}><option value="">كل الحالات</option><option value="ACTIVE">نشط</option><option value="SUSPENDED">معلّق</option><option value="DISABLED">معطّل</option></select><button className="secondary compact" onClick={() => void load()} disabled={loading}><RefreshCw size={14}/> تحديث</button></div>{loading ? <div className="empty">جارٍ تحميل المستخدمين…</div> : users.length === 0 ? <div className="empty">لا يوجد مستخدمون مطابقون.</div> : <div className="user-table">{users.map(user => <div className="user-row" key={user.id}><div><b>{user.display_name}</b><small>{user.username}{user.email ? ` · ${user.email}` : ''}</small></div><div className="user-roles">{user.roles.map(role => <span key={role}>{roleLabels[role] ?? role}</span>)}{user.scope_name && <span>{user.scope_name}</span>}</div><span className={`user-status ${user.status.toLowerCase()}`}>{statusLabels[user.status]}</span><div className="actions"><button className="link-button" onClick={() => { setEditing(user); setOpen(false); setForm({ ...blank, displayName: user.display_name, roleIds: roles.filter(role => user.roles.includes(role.name)).map(role => role.id), scopeType: user.scope_type, scopeId: user.scope_id ?? '' }); }}>تعديل الحساب</button><button className="link-button" onClick={() => void changeStatus(user)}>{user.status === 'ACTIVE' ? 'تعطيل' : 'تفعيل'}</button></div></div>)}</div>}</section>;
}
