import { API_BASE_URL } from './api-base';

export type AdminRole = { id: string; name: string; description: string | null };
export type ScopeType = 'NATIONAL' | 'ASSOCIATION' | 'DAIRA' | 'INSTITUTION';
export type AdminUser = { id: string; username: string; email: string | null; display_name: string; status: 'ACTIVE' | 'SUSPENDED' | 'DISABLED'; created_at: string; roles: string[]; scope_type: ScopeType | null; scope_id: string | null; scope_name: string | null };

export class UserAdminApiError extends Error { constructor(public code: string, message = 'تعذر إتمام العملية', public status?: number) { super(message); } }
export class UserAdminApi {
  constructor(private token: string, private fetcher: typeof fetch = fetch) {}
  private async request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await this.fetcher(`${API_BASE_URL}${path}`, { ...init, headers: { authorization: `Bearer ${this.token}`, ...(init.body ? { 'content-type': 'application/json' } : {}), ...(init.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) { const error = body?.error; throw new UserAdminApiError(typeof error === 'string' ? error : error?.code ?? 'INTERNAL_ERROR', 'تعذر إتمام العملية', response.status); } return body as T; }
  listUsers(params: { search?: string; status?: string; roleId?: string } = {}) { const query = new URLSearchParams(Object.entries(params).filter(([, value]) => value).map(([key, value]) => [key, String(value)])); return this.request<{ data: AdminUser[]; page: number; pageSize: number }>(`/api/v1/admin/users${query.size ? `?${query}` : ''}`); }
  listRoles() { return this.request<{ data: AdminRole[] }>('/api/v1/admin/roles'); }
  createUser(body: { username: string; email?: string; displayName: string; password: string; roleIds: string[] }) { return this.request<{ data: AdminUser }>('/api/v1/admin/users', { method: 'POST', body: JSON.stringify(body) }); }
  updateStatus(id: string, status: 'ACTIVE' | 'SUSPENDED' | 'DISABLED') { return this.request<{ data: Pick<AdminUser, 'id' | 'username' | 'status'> }>(`/api/v1/admin/users/${id}/status`, { method: 'POST', body: JSON.stringify({ status }) }); }
  updateProfile(id: string, displayName: string) { return this.request<{ data: Pick<AdminUser, 'id' | 'username' | 'email' | 'display_name' | 'status'> }>(`/api/v1/admin/users/${id}/profile`, { method: 'PATCH', body: JSON.stringify({ displayName }) }); }
  resetPassword(id: string, password: string) { return this.request<{ data: Pick<AdminUser, 'id' | 'username' | 'status'> }>(`/api/v1/admin/users/${id}/password-reset`, { method: 'POST', body: JSON.stringify({ password }) }); }
  updateRoles(id: string, roleIds: string[]) { return this.request<{ success: true }>(`/api/v1/admin/users/${id}/roles`, { method: 'PUT', body: JSON.stringify({ roleIds }) }); }
  updateAccess(id: string, roleIds: string[], scopeType: ScopeType | null, scopeId: string | null) { return this.request<{ data: { userId: string; scopeType: ScopeType | null; scopeId: string | null; scopeName: string | null } }>(`/api/v1/admin/users/${id}/access`, { method: 'PUT', body: JSON.stringify({ roleIds, scopeType, scopeId }) }); }
  listScopes(scopeType: ScopeType) { const path = scopeType === 'ASSOCIATION' ? '/api/v1/admin/competition-reference/organizations' : scopeType === 'DAIRA' ? '/api/v1/admin/competition-reference/dairas' : '/api/v1/admin/competition-reference/institutions'; return this.request<{ data: Array<{ id: string | number; label: string }> }>(path); }
}
export const roleLabels: Record<string, string> = { SYSTEM_ADMINISTRATOR: 'إداري عام', NATIONAL_ADMINISTRATOR: 'إداري وطني', ASSOCIATION_ADMINISTRATOR: 'مدير رابطة', ASSOCIATION_REPRESENTATIVE: 'ممثل رابطة', DAIRA_OFFICER: 'مسؤول دائرة', MEMBER_INSTITUTION_USER: 'مسؤول مؤسسة', PUBLIC_USER: 'مستخدم عام' };
export const statusLabels: Record<AdminUser['status'], string> = { ACTIVE: 'نشط', SUSPENDED: 'معلّق', DISABLED: 'معطّل' };
export function userAdminError(error: unknown) { if (error instanceof UserAdminApiError && error.code === 'forbidden') return 'ليس لديك صلاحية إدارة المستخدمين.'; if (error instanceof UserAdminApiError && error.code === 'username_or_email_exists') return 'اسم المستخدم أو البريد مستخدم مسبقاً.'; if (error instanceof UserAdminApiError && error.code === 'role_not_found') return 'اختر أدواراً صالحة.'; if (error instanceof UserAdminApiError && error.code === 'cannot_disable_current_user') return 'لا يمكنك تعطيل حسابك الحالي.'; if (error instanceof UserAdminApiError && error.code === 'validation_error') return 'تحقق من البيانات وكلمة المرور (12 محرفاً على الأقل).'; if (error instanceof UserAdminApiError && error.code === 'user_not_found') return 'المستخدم غير موجود.'; return 'تعذر إتمام العملية بأمان. حاول لاحقاً.'; }
